// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: switchmodule/switchmodule.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package openfmb.switchmodule;

@kotlin.jvm.JvmName("-initializeswitchStatusXSWI")
public inline fun switchStatusXSWI(block: openfmb.switchmodule.SwitchStatusXSWIKt.Dsl.() -> kotlin.Unit): openfmb.switchmodule.SwitchStatusXSWI =
  openfmb.switchmodule.SwitchStatusXSWIKt.Dsl._create(openfmb.switchmodule.SwitchStatusXSWI.newBuilder()).apply { block() }._build()
/**
 * ```
 * OpenFMB specialization for SwitchStatusProfile
 * ```
 *
 * Protobuf type `switchmodule.SwitchStatusXSWI`
 */
public object SwitchStatusXSWIKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: openfmb.switchmodule.SwitchStatusXSWI.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: openfmb.switchmodule.SwitchStatusXSWI.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): openfmb.switchmodule.SwitchStatusXSWI = _builder.build()

    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.LogicalNodeForEventAndStatus logicalNodeForEventAndStatus = 1 [(.uml.option_parent_message) = true];`
     */
    public var logicalNodeForEventAndStatus: openfmb.commonmodule.LogicalNodeForEventAndStatus
      @kotlin.jvm.JvmName("getLogicalNodeForEventAndStatus")
        get() = _builder.logicalNodeForEventAndStatus
      @kotlin.jvm.JvmName("setLogicalNodeForEventAndStatus")
        set(value) {
        _builder.logicalNodeForEventAndStatus = value
      }
    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.LogicalNodeForEventAndStatus logicalNodeForEventAndStatus = 1 [(.uml.option_parent_message) = true];`
     */
    public fun clearLogicalNodeForEventAndStatus() {
      _builder.clearLogicalNodeForEventAndStatus()
    }
    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.LogicalNodeForEventAndStatus logicalNodeForEventAndStatus = 1 [(.uml.option_parent_message) = true];`
     * @return Whether the logicalNodeForEventAndStatus field is set.
     */
    public fun hasLogicalNodeForEventAndStatus(): kotlin.Boolean {
      return _builder.hasLogicalNodeForEventAndStatus()
    }

    public val SwitchStatusXSWIKt.Dsl.logicalNodeForEventAndStatusOrNull: openfmb.commonmodule.LogicalNodeForEventAndStatus?
      get() = _builder.logicalNodeForEventAndStatusOrNull

    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.ENS_DynamicTestKind DynamicTest = 2;`
     */
    public var dynamicTest: openfmb.commonmodule.ENS_DynamicTestKind
      @kotlin.jvm.JvmName("getDynamicTest")
        get() = _builder.dynamicTest
      @kotlin.jvm.JvmName("setDynamicTest")
        set(value) {
        _builder.dynamicTest = value
      }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.ENS_DynamicTestKind DynamicTest = 2;`
     */
    public fun clearDynamicTest() {
      _builder.clearDynamicTest()
    }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.ENS_DynamicTestKind DynamicTest = 2;`
     * @return Whether the dynamicTest field is set.
     */
    public fun hasDynamicTest(): kotlin.Boolean {
      return _builder.hasDynamicTest()
    }

    public val SwitchStatusXSWIKt.Dsl.dynamicTestOrNull: openfmb.commonmodule.ENS_DynamicTestKind?
      get() = _builder.dynamicTestOrNull

    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.PhaseDPS Pos = 4;`
     */
    public var pos: openfmb.commonmodule.PhaseDPS
      @kotlin.jvm.JvmName("getPos")
        get() = _builder.pos
      @kotlin.jvm.JvmName("setPos")
        set(value) {
        _builder.pos = value
      }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.PhaseDPS Pos = 4;`
     */
    public fun clearPos() {
      _builder.clearPos()
    }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.PhaseDPS Pos = 4;`
     * @return Whether the pos field is set.
     */
    public fun hasPos(): kotlin.Boolean {
      return _builder.hasPos()
    }

    public val SwitchStatusXSWIKt.Dsl.posOrNull: openfmb.commonmodule.PhaseDPS?
      get() = _builder.posOrNull

    /**
     * ```
     * Fault latch: LT01=51A OR 51B OR 51C
     * ```
     *
     * `.commonmodule.PhaseSPS ProtectionPickup = 5 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];`
     */
    public var protectionPickup: openfmb.commonmodule.PhaseSPS
      @kotlin.jvm.JvmName("getProtectionPickup")
        get() = _builder.protectionPickup
      @kotlin.jvm.JvmName("setProtectionPickup")
        set(value) {
        _builder.protectionPickup = value
      }
    /**
     * ```
     * Fault latch: LT01=51A OR 51B OR 51C
     * ```
     *
     * `.commonmodule.PhaseSPS ProtectionPickup = 5 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];`
     */
    public fun clearProtectionPickup() {
      _builder.clearProtectionPickup()
    }
    /**
     * ```
     * Fault latch: LT01=51A OR 51B OR 51C
     * ```
     *
     * `.commonmodule.PhaseSPS ProtectionPickup = 5 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];`
     * @return Whether the protectionPickup field is set.
     */
    public fun hasProtectionPickup(): kotlin.Boolean {
      return _builder.hasProtectionPickup()
    }

    public val SwitchStatusXSWIKt.Dsl.protectionPickupOrNull: openfmb.commonmodule.PhaseSPS?
      get() = _builder.protectionPickupOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun openfmb.switchmodule.SwitchStatusXSWI.copy(block: `openfmb.switchmodule`.SwitchStatusXSWIKt.Dsl.() -> kotlin.Unit): openfmb.switchmodule.SwitchStatusXSWI =
  `openfmb.switchmodule`.SwitchStatusXSWIKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val openfmb.switchmodule.SwitchStatusXSWIOrBuilder.logicalNodeForEventAndStatusOrNull: openfmb.commonmodule.LogicalNodeForEventAndStatus?
  get() = if (hasLogicalNodeForEventAndStatus()) getLogicalNodeForEventAndStatus() else null

public val openfmb.switchmodule.SwitchStatusXSWIOrBuilder.dynamicTestOrNull: openfmb.commonmodule.ENS_DynamicTestKind?
  get() = if (hasDynamicTest()) getDynamicTest() else null

public val openfmb.switchmodule.SwitchStatusXSWIOrBuilder.posOrNull: openfmb.commonmodule.PhaseDPS?
  get() = if (hasPos()) getPos() else null

public val openfmb.switchmodule.SwitchStatusXSWIOrBuilder.protectionPickupOrNull: openfmb.commonmodule.PhaseSPS?
  get() = if (hasProtectionPickup()) getProtectionPickup() else null

