// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: switchmodule/switchmodule.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package openfmb.switchmodule;

@kotlin.jvm.JvmName("-initializeswitchDiscreteControlXSWI")
public inline fun switchDiscreteControlXSWI(block: openfmb.switchmodule.SwitchDiscreteControlXSWIKt.Dsl.() -> kotlin.Unit): openfmb.switchmodule.SwitchDiscreteControlXSWI =
  openfmb.switchmodule.SwitchDiscreteControlXSWIKt.Dsl._create(openfmb.switchmodule.SwitchDiscreteControlXSWI.newBuilder()).apply { block() }._build()
/**
 * ```
 * OpenFMB specialization for switch control:  LN: Circuit switch   Name: XSWI
 * ```
 *
 * Protobuf type `switchmodule.SwitchDiscreteControlXSWI`
 */
public object SwitchDiscreteControlXSWIKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: openfmb.switchmodule.SwitchDiscreteControlXSWI.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: openfmb.switchmodule.SwitchDiscreteControlXSWI.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): openfmb.switchmodule.SwitchDiscreteControlXSWI = _builder.build()

    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.LogicalNodeForControl logicalNodeForControl = 1 [(.uml.option_parent_message) = true];`
     */
    public var logicalNodeForControl: openfmb.commonmodule.LogicalNodeForControl
      @kotlin.jvm.JvmName("getLogicalNodeForControl")
        get() = _builder.logicalNodeForControl
      @kotlin.jvm.JvmName("setLogicalNodeForControl")
        set(value) {
        _builder.logicalNodeForControl = value
      }
    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.LogicalNodeForControl logicalNodeForControl = 1 [(.uml.option_parent_message) = true];`
     */
    public fun clearLogicalNodeForControl() {
      _builder.clearLogicalNodeForControl()
    }
    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.LogicalNodeForControl logicalNodeForControl = 1 [(.uml.option_parent_message) = true];`
     * @return Whether the logicalNodeForControl field is set.
     */
    public fun hasLogicalNodeForControl(): kotlin.Boolean {
      return _builder.hasLogicalNodeForControl()
    }

    public val SwitchDiscreteControlXSWIKt.Dsl.logicalNodeForControlOrNull: openfmb.commonmodule.LogicalNodeForControl?
      get() = _builder.logicalNodeForControlOrNull

    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.PhaseDPC Pos = 2;`
     */
    public var pos: openfmb.commonmodule.PhaseDPC
      @kotlin.jvm.JvmName("getPos")
        get() = _builder.pos
      @kotlin.jvm.JvmName("setPos")
        set(value) {
        _builder.pos = value
      }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.PhaseDPC Pos = 2;`
     */
    public fun clearPos() {
      _builder.clearPos()
    }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.PhaseDPC Pos = 2;`
     * @return Whether the pos field is set.
     */
    public fun hasPos(): kotlin.Boolean {
      return _builder.hasPos()
    }

    public val SwitchDiscreteControlXSWIKt.Dsl.posOrNull: openfmb.commonmodule.PhaseDPC?
      get() = _builder.posOrNull

    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.ControlSPC ResetProtectionPickup = 3;`
     */
    public var resetProtectionPickup: openfmb.commonmodule.ControlSPC
      @kotlin.jvm.JvmName("getResetProtectionPickup")
        get() = _builder.resetProtectionPickup
      @kotlin.jvm.JvmName("setResetProtectionPickup")
        set(value) {
        _builder.resetProtectionPickup = value
      }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.ControlSPC ResetProtectionPickup = 3;`
     */
    public fun clearResetProtectionPickup() {
      _builder.clearResetProtectionPickup()
    }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.ControlSPC ResetProtectionPickup = 3;`
     * @return Whether the resetProtectionPickup field is set.
     */
    public fun hasResetProtectionPickup(): kotlin.Boolean {
      return _builder.hasResetProtectionPickup()
    }

    public val SwitchDiscreteControlXSWIKt.Dsl.resetProtectionPickupOrNull: openfmb.commonmodule.ControlSPC?
      get() = _builder.resetProtectionPickupOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun openfmb.switchmodule.SwitchDiscreteControlXSWI.copy(block: `openfmb.switchmodule`.SwitchDiscreteControlXSWIKt.Dsl.() -> kotlin.Unit): openfmb.switchmodule.SwitchDiscreteControlXSWI =
  `openfmb.switchmodule`.SwitchDiscreteControlXSWIKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val openfmb.switchmodule.SwitchDiscreteControlXSWIOrBuilder.logicalNodeForControlOrNull: openfmb.commonmodule.LogicalNodeForControl?
  get() = if (hasLogicalNodeForControl()) getLogicalNodeForControl() else null

public val openfmb.switchmodule.SwitchDiscreteControlXSWIOrBuilder.posOrNull: openfmb.commonmodule.PhaseDPC?
  get() = if (hasPos()) getPos() else null

public val openfmb.switchmodule.SwitchDiscreteControlXSWIOrBuilder.resetProtectionPickupOrNull: openfmb.commonmodule.ControlSPC?
  get() = if (hasResetProtectionPickup()) getResetProtectionPickup() else null

