//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: capbankmodule/capbankmodule.proto

package openfmb.capbankmodule;

@kotlin.jvm.JvmName("-initializecapBankDiscreteControl")
public inline fun capBankDiscreteControl(block: openfmb.capbankmodule.CapBankDiscreteControlKt.Dsl.() -> kotlin.Unit): openfmb.capbankmodule.CapBankDiscreteControl =
  openfmb.capbankmodule.CapBankDiscreteControlKt.Dsl._create(openfmb.capbankmodule.CapBankDiscreteControl.newBuilder()).apply { block() }._build()
public object CapBankDiscreteControlKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: openfmb.capbankmodule.CapBankDiscreteControl.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: openfmb.capbankmodule.CapBankDiscreteControl.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): openfmb.capbankmodule.CapBankDiscreteControl = _builder.build()

    /**
     * <pre>
     * UML inherited base object
     * </pre>
     *
     * <code>.commonmodule.ControlValue controlValue = 1 [(.uml.option_parent_message) = true];</code>
     */
    public var controlValue: openfmb.commonmodule.ControlValue
      @JvmName("getControlValue")
      get() = _builder.getControlValue()
      @JvmName("setControlValue")
      set(value) {
        _builder.setControlValue(value)
      }
    /**
     * <pre>
     * UML inherited base object
     * </pre>
     *
     * <code>.commonmodule.ControlValue controlValue = 1 [(.uml.option_parent_message) = true];</code>
     */
    public fun clearControlValue() {
      _builder.clearControlValue()
    }
    /**
     * <pre>
     * UML inherited base object
     * </pre>
     *
     * <code>.commonmodule.ControlValue controlValue = 1 [(.uml.option_parent_message) = true];</code>
     * @return Whether the controlValue field is set.
     */
    public fun hasControlValue(): kotlin.Boolean {
      return _builder.hasControlValue()
    }

    /**
     * <pre>
     * MISSING DOCUMENTATION!!!
     * </pre>
     *
     * <code>.commonmodule.CheckConditions check = 2;</code>
     */
    public var check: openfmb.commonmodule.CheckConditions
      @JvmName("getCheck")
      get() = _builder.getCheck()
      @JvmName("setCheck")
      set(value) {
        _builder.setCheck(value)
      }
    /**
     * <pre>
     * MISSING DOCUMENTATION!!!
     * </pre>
     *
     * <code>.commonmodule.CheckConditions check = 2;</code>
     */
    public fun clearCheck() {
      _builder.clearCheck()
    }
    /**
     * <pre>
     * MISSING DOCUMENTATION!!!
     * </pre>
     *
     * <code>.commonmodule.CheckConditions check = 2;</code>
     * @return Whether the check field is set.
     */
    public fun hasCheck(): kotlin.Boolean {
      return _builder.hasCheck()
    }

    /**
     * <pre>
     * MISSING DOCUMENTATION!!!
     * </pre>
     *
     * <code>.capbankmodule.CapBankDiscreteControlYPSH capBankDiscreteControlYPSH = 3;</code>
     */
    public var capBankDiscreteControlYPSH: openfmb.capbankmodule.CapBankDiscreteControlYPSH
      @JvmName("getCapBankDiscreteControlYPSH")
      get() = _builder.getCapBankDiscreteControlYPSH()
      @JvmName("setCapBankDiscreteControlYPSH")
      set(value) {
        _builder.setCapBankDiscreteControlYPSH(value)
      }
    /**
     * <pre>
     * MISSING DOCUMENTATION!!!
     * </pre>
     *
     * <code>.capbankmodule.CapBankDiscreteControlYPSH capBankDiscreteControlYPSH = 3;</code>
     */
    public fun clearCapBankDiscreteControlYPSH() {
      _builder.clearCapBankDiscreteControlYPSH()
    }
    /**
     * <pre>
     * MISSING DOCUMENTATION!!!
     * </pre>
     *
     * <code>.capbankmodule.CapBankDiscreteControlYPSH capBankDiscreteControlYPSH = 3;</code>
     * @return Whether the capBankDiscreteControlYPSH field is set.
     */
    public fun hasCapBankDiscreteControlYPSH(): kotlin.Boolean {
      return _builder.hasCapBankDiscreteControlYPSH()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun openfmb.capbankmodule.CapBankDiscreteControl.copy(block: openfmb.capbankmodule.CapBankDiscreteControlKt.Dsl.() -> kotlin.Unit): openfmb.capbankmodule.CapBankDiscreteControl =
  openfmb.capbankmodule.CapBankDiscreteControlKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val openfmb.capbankmodule.CapBankDiscreteControlOrBuilder.controlValueOrNull: openfmb.commonmodule.ControlValue?
  get() = if (hasControlValue()) getControlValue() else null

public val openfmb.capbankmodule.CapBankDiscreteControlOrBuilder.checkOrNull: openfmb.commonmodule.CheckConditions?
  get() = if (hasCheck()) getCheck() else null

public val openfmb.capbankmodule.CapBankDiscreteControlOrBuilder.capBankDiscreteControlYPSHOrNull: openfmb.capbankmodule.CapBankDiscreteControlYPSH?
  get() = if (hasCapBankDiscreteControlYPSH()) getCapBankDiscreteControlYPSH() else null

