//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: capbankmodule/capbankmodule.proto

package openfmb.capbankmodule;

@kotlin.jvm.JvmName("-initializecapBankEvent")
public inline fun capBankEvent(block: openfmb.capbankmodule.CapBankEventKt.Dsl.() -> kotlin.Unit): openfmb.capbankmodule.CapBankEvent =
  openfmb.capbankmodule.CapBankEventKt.Dsl._create(openfmb.capbankmodule.CapBankEvent.newBuilder()).apply { block() }._build()
public object CapBankEventKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: openfmb.capbankmodule.CapBankEvent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: openfmb.capbankmodule.CapBankEvent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): openfmb.capbankmodule.CapBankEvent = _builder.build()

    /**
     * <pre>
     * UML inherited base object
     * </pre>
     *
     * <code>.commonmodule.EventValue eventValue = 1 [(.uml.option_parent_message) = true];</code>
     */
    public var eventValue: openfmb.commonmodule.EventValue
      @JvmName("getEventValue")
      get() = _builder.getEventValue()
      @JvmName("setEventValue")
      set(value) {
        _builder.setEventValue(value)
      }
    /**
     * <pre>
     * UML inherited base object
     * </pre>
     *
     * <code>.commonmodule.EventValue eventValue = 1 [(.uml.option_parent_message) = true];</code>
     */
    public fun clearEventValue() {
      _builder.clearEventValue()
    }
    /**
     * <pre>
     * UML inherited base object
     * </pre>
     *
     * <code>.commonmodule.EventValue eventValue = 1 [(.uml.option_parent_message) = true];</code>
     * @return Whether the eventValue field is set.
     */
    public fun hasEventValue(): kotlin.Boolean {
      return _builder.hasEventValue()
    }

    /**
     * <pre>
     * MISSING DOCUMENTATION!!!
     * </pre>
     *
     * <code>.capbankmodule.CapBankEventAndStatusYPSH CapBankEventAndStatusYPSH = 2;</code>
     */
    public var capBankEventAndStatusYPSH: openfmb.capbankmodule.CapBankEventAndStatusYPSH
      @JvmName("getCapBankEventAndStatusYPSH")
      get() = _builder.getCapBankEventAndStatusYPSH()
      @JvmName("setCapBankEventAndStatusYPSH")
      set(value) {
        _builder.setCapBankEventAndStatusYPSH(value)
      }
    /**
     * <pre>
     * MISSING DOCUMENTATION!!!
     * </pre>
     *
     * <code>.capbankmodule.CapBankEventAndStatusYPSH CapBankEventAndStatusYPSH = 2;</code>
     */
    public fun clearCapBankEventAndStatusYPSH() {
      _builder.clearCapBankEventAndStatusYPSH()
    }
    /**
     * <pre>
     * MISSING DOCUMENTATION!!!
     * </pre>
     *
     * <code>.capbankmodule.CapBankEventAndStatusYPSH CapBankEventAndStatusYPSH = 2;</code>
     * @return Whether the capBankEventAndStatusYPSH field is set.
     */
    public fun hasCapBankEventAndStatusYPSH(): kotlin.Boolean {
      return _builder.hasCapBankEventAndStatusYPSH()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun openfmb.capbankmodule.CapBankEvent.copy(block: openfmb.capbankmodule.CapBankEventKt.Dsl.() -> kotlin.Unit): openfmb.capbankmodule.CapBankEvent =
  openfmb.capbankmodule.CapBankEventKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val openfmb.capbankmodule.CapBankEventOrBuilder.eventValueOrNull: openfmb.commonmodule.EventValue?
  get() = if (hasEventValue()) getEventValue() else null

public val openfmb.capbankmodule.CapBankEventOrBuilder.capBankEventAndStatusYPSHOrNull: openfmb.capbankmodule.CapBankEventAndStatusYPSH?
  get() = if (hasCapBankEventAndStatusYPSH()) getCapBankEventAndStatusYPSH() else null

