// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: capbankmodule/capbankmodule.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package openfmb.capbankmodule;

@kotlin.jvm.JvmName("-initializecapBankReadingProfile")
public inline fun capBankReadingProfile(block: openfmb.capbankmodule.CapBankReadingProfileKt.Dsl.() -> kotlin.Unit): openfmb.capbankmodule.CapBankReadingProfile =
  openfmb.capbankmodule.CapBankReadingProfileKt.Dsl._create(openfmb.capbankmodule.CapBankReadingProfile.newBuilder()).apply { block() }._build()
/**
 * ```
 * Cap bank reading profile
 * ```
 *
 * Protobuf type `capbankmodule.CapBankReadingProfile`
 */
public object CapBankReadingProfileKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: openfmb.capbankmodule.CapBankReadingProfile.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: openfmb.capbankmodule.CapBankReadingProfile.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): openfmb.capbankmodule.CapBankReadingProfile = _builder.build()

    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.ReadingMessageInfo readingMessageInfo = 1 [(.uml.option_parent_message) = true];`
     */
    public var readingMessageInfo: openfmb.commonmodule.ReadingMessageInfo
      @JvmName("getReadingMessageInfo")
      get() = _builder.getReadingMessageInfo()
      @JvmName("setReadingMessageInfo")
      set(value) {
        _builder.setReadingMessageInfo(value)
      }
    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.ReadingMessageInfo readingMessageInfo = 1 [(.uml.option_parent_message) = true];`
     */
    public fun clearReadingMessageInfo() {
      _builder.clearReadingMessageInfo()
    }
    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.ReadingMessageInfo readingMessageInfo = 1 [(.uml.option_parent_message) = true];`
     * @return Whether the readingMessageInfo field is set.
     */
    public fun hasReadingMessageInfo(): kotlin.Boolean {
      return _builder.hasReadingMessageInfo()
    }

    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.capbankmodule.CapBankReading capBankReading = 2 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];`
     */
    public var capBankReading: openfmb.capbankmodule.CapBankReading
      @JvmName("getCapBankReading")
      get() = _builder.getCapBankReading()
      @JvmName("setCapBankReading")
      set(value) {
        _builder.setCapBankReading(value)
      }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.capbankmodule.CapBankReading capBankReading = 2 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];`
     */
    public fun clearCapBankReading() {
      _builder.clearCapBankReading()
    }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.capbankmodule.CapBankReading capBankReading = 2 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];`
     * @return Whether the capBankReading field is set.
     */
    public fun hasCapBankReading(): kotlin.Boolean {
      return _builder.hasCapBankReading()
    }

    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.capbankmodule.CapBankSystem capBankSystem = 3 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];`
     */
    public var capBankSystem: openfmb.capbankmodule.CapBankSystem
      @JvmName("getCapBankSystem")
      get() = _builder.getCapBankSystem()
      @JvmName("setCapBankSystem")
      set(value) {
        _builder.setCapBankSystem(value)
      }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.capbankmodule.CapBankSystem capBankSystem = 3 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];`
     */
    public fun clearCapBankSystem() {
      _builder.clearCapBankSystem()
    }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.capbankmodule.CapBankSystem capBankSystem = 3 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];`
     * @return Whether the capBankSystem field is set.
     */
    public fun hasCapBankSystem(): kotlin.Boolean {
      return _builder.hasCapBankSystem()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun openfmb.capbankmodule.CapBankReadingProfile.copy(block: openfmb.capbankmodule.CapBankReadingProfileKt.Dsl.() -> kotlin.Unit): openfmb.capbankmodule.CapBankReadingProfile =
  openfmb.capbankmodule.CapBankReadingProfileKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val openfmb.capbankmodule.CapBankReadingProfileOrBuilder.readingMessageInfoOrNull: openfmb.commonmodule.ReadingMessageInfo?
  get() = if (hasReadingMessageInfo()) getReadingMessageInfo() else null

public val openfmb.capbankmodule.CapBankReadingProfileOrBuilder.capBankReadingOrNull: openfmb.capbankmodule.CapBankReading?
  get() = if (hasCapBankReading()) getCapBankReading() else null

public val openfmb.capbankmodule.CapBankReadingProfileOrBuilder.capBankSystemOrNull: openfmb.capbankmodule.CapBankSystem?
  get() = if (hasCapBankSystem()) getCapBankSystem() else null

