// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: commonmodule/commonmodule.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package openfmb.commonmodule;

@kotlin.jvm.JvmName("-initializeactivePower")
public inline fun activePower(block: openfmb.commonmodule.ActivePowerKt.Dsl.() -> kotlin.Unit): openfmb.commonmodule.ActivePower =
  openfmb.commonmodule.ActivePowerKt.Dsl._create(openfmb.commonmodule.ActivePower.newBuilder()).apply { block() }._build()
/**
 * ```
 * MISSING DOCUMENTATION!!!
 * ```
 *
 * Protobuf type `commonmodule.ActivePower`
 */
public object ActivePowerKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: openfmb.commonmodule.ActivePower.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: openfmb.commonmodule.ActivePower.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): openfmb.commonmodule.ActivePower = _builder.build()

    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.Optional_UnitMultiplierKind multiplier = 1;`
     */
    public var multiplier: openfmb.commonmodule.Optional_UnitMultiplierKind
      @kotlin.jvm.JvmName("getMultiplier")
        get() = _builder.multiplier
      @kotlin.jvm.JvmName("setMultiplier")
        set(value) {
        _builder.multiplier = value
      }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.Optional_UnitMultiplierKind multiplier = 1;`
     */
    public fun clearMultiplier() {
      _builder.clearMultiplier()
    }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.Optional_UnitMultiplierKind multiplier = 1;`
     * @return Whether the multiplier field is set.
     */
    public fun hasMultiplier(): kotlin.Boolean {
      return _builder.hasMultiplier()
    }

    public val ActivePowerKt.Dsl.multiplierOrNull: openfmb.commonmodule.Optional_UnitMultiplierKind?
      get() = _builder.multiplierOrNull

    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.Optional_UnitSymbolKind unit = 2;`
     */
    public var unit: openfmb.commonmodule.Optional_UnitSymbolKind
      @kotlin.jvm.JvmName("getUnit")
        get() = _builder.unit
      @kotlin.jvm.JvmName("setUnit")
        set(value) {
        _builder.unit = value
      }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.Optional_UnitSymbolKind unit = 2;`
     */
    public fun clearUnit() {
      _builder.clearUnit()
    }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.Optional_UnitSymbolKind unit = 2;`
     * @return Whether the unit field is set.
     */
    public fun hasUnit(): kotlin.Boolean {
      return _builder.hasUnit()
    }

    public val ActivePowerKt.Dsl.unitOrNull: openfmb.commonmodule.Optional_UnitSymbolKind?
      get() = _builder.unitOrNull

    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.google.protobuf.FloatValue value = 3;`
     */
    public var value: com.google.protobuf.FloatValue
      @kotlin.jvm.JvmName("getValue")
        get() = _builder.value
      @kotlin.jvm.JvmName("setValue")
        set(value) {
        _builder.value = value
      }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.google.protobuf.FloatValue value = 3;`
     */
    public fun clearValue() {
      _builder.clearValue()
    }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.google.protobuf.FloatValue value = 3;`
     * @return Whether the value field is set.
     */
    public fun hasValue(): kotlin.Boolean {
      return _builder.hasValue()
    }

    public val ActivePowerKt.Dsl.valueOrNull: com.google.protobuf.FloatValue?
      get() = _builder.valueOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun openfmb.commonmodule.ActivePower.copy(block: `openfmb.commonmodule`.ActivePowerKt.Dsl.() -> kotlin.Unit): openfmb.commonmodule.ActivePower =
  `openfmb.commonmodule`.ActivePowerKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val openfmb.commonmodule.ActivePowerOrBuilder.multiplierOrNull: openfmb.commonmodule.Optional_UnitMultiplierKind?
  get() = if (hasMultiplier()) getMultiplier() else null

public val openfmb.commonmodule.ActivePowerOrBuilder.unitOrNull: openfmb.commonmodule.Optional_UnitSymbolKind?
  get() = if (hasUnit()) getUnit() else null

public val openfmb.commonmodule.ActivePowerOrBuilder.valueOrNull: com.google.protobuf.FloatValue?
  get() = if (hasValue()) getValue() else null

