// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: commonmodule/commonmodule.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package openfmb.commonmodule;

@kotlin.jvm.JvmName("-initializedateTimeInterval")
public inline fun dateTimeInterval(block: openfmb.commonmodule.DateTimeIntervalKt.Dsl.() -> kotlin.Unit): openfmb.commonmodule.DateTimeInterval =
  openfmb.commonmodule.DateTimeIntervalKt.Dsl._create(openfmb.commonmodule.DateTimeInterval.newBuilder()).apply { block() }._build()
/**
 * ```
 * Interval between two date and time points.
 * ```
 *
 * Protobuf type `commonmodule.DateTimeInterval`
 */
public object DateTimeIntervalKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: openfmb.commonmodule.DateTimeInterval.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: openfmb.commonmodule.DateTimeInterval.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): openfmb.commonmodule.DateTimeInterval = _builder.build()

    /**
     * ```
     * End date and time of this interval.
     * ```
     *
     * `.google.protobuf.Int64Value end = 1;`
     */
    public var end: com.google.protobuf.Int64Value
      @kotlin.jvm.JvmName("getEnd")
        get() = _builder.end
      @kotlin.jvm.JvmName("setEnd")
        set(value) {
        _builder.end = value
      }
    /**
     * ```
     * End date and time of this interval.
     * ```
     *
     * `.google.protobuf.Int64Value end = 1;`
     */
    public fun clearEnd() {
      _builder.clearEnd()
    }
    /**
     * ```
     * End date and time of this interval.
     * ```
     *
     * `.google.protobuf.Int64Value end = 1;`
     * @return Whether the end field is set.
     */
    public fun hasEnd(): kotlin.Boolean {
      return _builder.hasEnd()
    }

    public val DateTimeIntervalKt.Dsl.endOrNull: com.google.protobuf.Int64Value?
      get() = _builder.endOrNull

    /**
     * ```
     * Start date and time of this interval.
     * ```
     *
     * `.google.protobuf.Int64Value start = 2;`
     */
    public var start: com.google.protobuf.Int64Value
      @kotlin.jvm.JvmName("getStart")
        get() = _builder.start
      @kotlin.jvm.JvmName("setStart")
        set(value) {
        _builder.start = value
      }
    /**
     * ```
     * Start date and time of this interval.
     * ```
     *
     * `.google.protobuf.Int64Value start = 2;`
     */
    public fun clearStart() {
      _builder.clearStart()
    }
    /**
     * ```
     * Start date and time of this interval.
     * ```
     *
     * `.google.protobuf.Int64Value start = 2;`
     * @return Whether the start field is set.
     */
    public fun hasStart(): kotlin.Boolean {
      return _builder.hasStart()
    }

    public val DateTimeIntervalKt.Dsl.startOrNull: com.google.protobuf.Int64Value?
      get() = _builder.startOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun openfmb.commonmodule.DateTimeInterval.copy(block: `openfmb.commonmodule`.DateTimeIntervalKt.Dsl.() -> kotlin.Unit): openfmb.commonmodule.DateTimeInterval =
  `openfmb.commonmodule`.DateTimeIntervalKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val openfmb.commonmodule.DateTimeIntervalOrBuilder.endOrNull: com.google.protobuf.Int64Value?
  get() = if (hasEnd()) getEnd() else null

public val openfmb.commonmodule.DateTimeIntervalOrBuilder.startOrNull: com.google.protobuf.Int64Value?
  get() = if (hasStart()) getStart() else null

