// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: commonmodule/commonmodule.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package openfmb.commonmodule;

@kotlin.jvm.JvmName("-initializeeNGGridConnectModeKind")
public inline fun eNGGridConnectModeKind(block: openfmb.commonmodule.ENG_GridConnectModeKindKt.Dsl.() -> kotlin.Unit): openfmb.commonmodule.ENG_GridConnectModeKind =
  openfmb.commonmodule.ENG_GridConnectModeKindKt.Dsl._create(openfmb.commonmodule.ENG_GridConnectModeKind.newBuilder()).apply { block() }._build()
/**
 * ```
 * Grid connect mode kind
 * ```
 *
 * Protobuf type `commonmodule.ENG_GridConnectModeKind`
 */
public object ENG_GridConnectModeKindKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: openfmb.commonmodule.ENG_GridConnectModeKind.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: openfmb.commonmodule.ENG_GridConnectModeKind.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): openfmb.commonmodule.ENG_GridConnectModeKind = _builder.build()

    /**
     * ```
     * The value of the status setting.
     * ```
     *
     * `.commonmodule.GridConnectModeKind setVal = 1 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];`
     */
    public var setVal: openfmb.commonmodule.GridConnectModeKind
      @kotlin.jvm.JvmName("getSetVal")
        get() = _builder.setVal
      @kotlin.jvm.JvmName("setSetVal")
        set(value) {
        _builder.setVal = value
      }
    public var setValValue: kotlin.Int
      @kotlin.jvm.JvmName("getSetValValue")
        get() = _builder.setValValue
      @kotlin.jvm.JvmName("setSetValValue")
        set(value) {
        _builder.setValValue = value
      }
    /**
     * ```
     * The value of the status setting.
     * ```
     *
     * `.commonmodule.GridConnectModeKind setVal = 1 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];`
     */
    public fun clearSetVal() {
      _builder.clearSetVal()
    }

    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.google.protobuf.StringValue setValExtension = 2;`
     */
    public var setValExtension: com.google.protobuf.StringValue
      @kotlin.jvm.JvmName("getSetValExtension")
        get() = _builder.setValExtension
      @kotlin.jvm.JvmName("setSetValExtension")
        set(value) {
        _builder.setValExtension = value
      }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.google.protobuf.StringValue setValExtension = 2;`
     */
    public fun clearSetValExtension() {
      _builder.clearSetValExtension()
    }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.google.protobuf.StringValue setValExtension = 2;`
     * @return Whether the setValExtension field is set.
     */
    public fun hasSetValExtension(): kotlin.Boolean {
      return _builder.hasSetValExtension()
    }

    public val ENG_GridConnectModeKindKt.Dsl.setValExtensionOrNull: com.google.protobuf.StringValue?
      get() = _builder.setValExtensionOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun openfmb.commonmodule.ENG_GridConnectModeKind.copy(block: `openfmb.commonmodule`.ENG_GridConnectModeKindKt.Dsl.() -> kotlin.Unit): openfmb.commonmodule.ENG_GridConnectModeKind =
  `openfmb.commonmodule`.ENG_GridConnectModeKindKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val openfmb.commonmodule.ENG_GridConnectModeKindOrBuilder.setValExtensionOrNull: com.google.protobuf.StringValue?
  get() = if (hasSetValExtension()) getSetValExtension() else null

