// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: commonmodule/commonmodule.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package openfmb.commonmodule;

@kotlin.jvm.JvmName("-initializeeNSBehaviourModeKind")
public inline fun eNSBehaviourModeKind(block: openfmb.commonmodule.ENS_BehaviourModeKindKt.Dsl.() -> kotlin.Unit): openfmb.commonmodule.ENS_BehaviourModeKind =
  openfmb.commonmodule.ENS_BehaviourModeKindKt.Dsl._create(openfmb.commonmodule.ENS_BehaviourModeKind.newBuilder()).apply { block() }._build()
/**
 * ```
 * Behavior mode kind. ENS stands for Enumerated status
 * ```
 *
 * Protobuf type `commonmodule.ENS_BehaviourModeKind`
 */
public object ENS_BehaviourModeKindKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: openfmb.commonmodule.ENS_BehaviourModeKind.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: openfmb.commonmodule.ENS_BehaviourModeKind.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): openfmb.commonmodule.ENS_BehaviourModeKind = _builder.build()

    /**
     * ```
     * Quality of the value in 'stVal'.
     * ```
     *
     * `.commonmodule.Quality q = 1;`
     */
    public var q: openfmb.commonmodule.Quality
      @kotlin.jvm.JvmName("getQ")
        get() = _builder.q
      @kotlin.jvm.JvmName("setQ")
        set(value) {
        _builder.q = value
      }
    /**
     * ```
     * Quality of the value in 'stVal'.
     * ```
     *
     * `.commonmodule.Quality q = 1;`
     */
    public fun clearQ() {
      _builder.clearQ()
    }
    /**
     * ```
     * Quality of the value in 'stVal'.
     * ```
     *
     * `.commonmodule.Quality q = 1;`
     * @return Whether the q field is set.
     */
    public fun hasQ(): kotlin.Boolean {
      return _builder.hasQ()
    }

    public val ENS_BehaviourModeKindKt.Dsl.qOrNull: openfmb.commonmodule.Quality?
      get() = _builder.qOrNull

    /**
     * ```
     * Value of the data.
     * ```
     *
     * `.commonmodule.BehaviourModeKind stVal = 2 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];`
     */
    public var stVal: openfmb.commonmodule.BehaviourModeKind
      @kotlin.jvm.JvmName("getStVal")
        get() = _builder.stVal
      @kotlin.jvm.JvmName("setStVal")
        set(value) {
        _builder.stVal = value
      }
    public var stValValue: kotlin.Int
      @kotlin.jvm.JvmName("getStValValue")
        get() = _builder.stValValue
      @kotlin.jvm.JvmName("setStValValue")
        set(value) {
        _builder.stValValue = value
      }
    /**
     * ```
     * Value of the data.
     * ```
     *
     * `.commonmodule.BehaviourModeKind stVal = 2 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];`
     */
    public fun clearStVal() {
      _builder.clearStVal()
    }

    /**
     * ```
     * Timestamp of the last change or update event of 'stVal' or the last change of value in 'q'.
     * ```
     *
     * `.commonmodule.Timestamp t = 3;`
     */
    public var t: openfmb.commonmodule.Timestamp
      @kotlin.jvm.JvmName("getT")
        get() = _builder.t
      @kotlin.jvm.JvmName("setT")
        set(value) {
        _builder.t = value
      }
    /**
     * ```
     * Timestamp of the last change or update event of 'stVal' or the last change of value in 'q'.
     * ```
     *
     * `.commonmodule.Timestamp t = 3;`
     */
    public fun clearT() {
      _builder.clearT()
    }
    /**
     * ```
     * Timestamp of the last change or update event of 'stVal' or the last change of value in 'q'.
     * ```
     *
     * `.commonmodule.Timestamp t = 3;`
     * @return Whether the t field is set.
     */
    public fun hasT(): kotlin.Boolean {
      return _builder.hasT()
    }

    public val ENS_BehaviourModeKindKt.Dsl.tOrNull: openfmb.commonmodule.Timestamp?
      get() = _builder.tOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun openfmb.commonmodule.ENS_BehaviourModeKind.copy(block: `openfmb.commonmodule`.ENS_BehaviourModeKindKt.Dsl.() -> kotlin.Unit): openfmb.commonmodule.ENS_BehaviourModeKind =
  `openfmb.commonmodule`.ENS_BehaviourModeKindKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val openfmb.commonmodule.ENS_BehaviourModeKindOrBuilder.qOrNull: openfmb.commonmodule.Quality?
  get() = if (hasQ()) getQ() else null

public val openfmb.commonmodule.ENS_BehaviourModeKindOrBuilder.tOrNull: openfmb.commonmodule.Timestamp?
  get() = if (hasT()) getT() else null

