// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: commonmodule/commonmodule.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package openfmb.commonmodule;

@kotlin.jvm.JvmName("-initializeeNSSwitchingCapabilityKind")
public inline fun eNSSwitchingCapabilityKind(block: openfmb.commonmodule.ENS_SwitchingCapabilityKindKt.Dsl.() -> kotlin.Unit): openfmb.commonmodule.ENS_SwitchingCapabilityKind =
  openfmb.commonmodule.ENS_SwitchingCapabilityKindKt.Dsl._create(openfmb.commonmodule.ENS_SwitchingCapabilityKind.newBuilder()).apply { block() }._build()
/**
 * ```
 * <<abstract>> Enumerated status (ENS)
 * ```
 *
 * Protobuf type `commonmodule.ENS_SwitchingCapabilityKind`
 */
public object ENS_SwitchingCapabilityKindKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: openfmb.commonmodule.ENS_SwitchingCapabilityKind.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: openfmb.commonmodule.ENS_SwitchingCapabilityKind.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): openfmb.commonmodule.ENS_SwitchingCapabilityKind = _builder.build()

    /**
     * ```
     * If true, 'q.operatorBlocked'=true, and the process value is no longer updated.
     * ```
     *
     * `.google.protobuf.BoolValue blkEna = 1;`
     */
    public var blkEna: com.google.protobuf.BoolValue
      @kotlin.jvm.JvmName("getBlkEna")
        get() = _builder.blkEna
      @kotlin.jvm.JvmName("setBlkEna")
        set(value) {
        _builder.blkEna = value
      }
    /**
     * ```
     * If true, 'q.operatorBlocked'=true, and the process value is no longer updated.
     * ```
     *
     * `.google.protobuf.BoolValue blkEna = 1;`
     */
    public fun clearBlkEna() {
      _builder.clearBlkEna()
    }
    /**
     * ```
     * If true, 'q.operatorBlocked'=true, and the process value is no longer updated.
     * ```
     *
     * `.google.protobuf.BoolValue blkEna = 1;`
     * @return Whether the blkEna field is set.
     */
    public fun hasBlkEna(): kotlin.Boolean {
      return _builder.hasBlkEna()
    }

    public val ENS_SwitchingCapabilityKindKt.Dsl.blkEnaOrNull: com.google.protobuf.BoolValue?
      get() = _builder.blkEnaOrNull

    /**
     * ```
     * Value of the data.
     * ```
     *
     * `.commonmodule.SwitchingCapabilityKind stVal = 2 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];`
     */
    public var stVal: openfmb.commonmodule.SwitchingCapabilityKind
      @kotlin.jvm.JvmName("getStVal")
        get() = _builder.stVal
      @kotlin.jvm.JvmName("setStVal")
        set(value) {
        _builder.stVal = value
      }
    public var stValValue: kotlin.Int
      @kotlin.jvm.JvmName("getStValValue")
        get() = _builder.stValValue
      @kotlin.jvm.JvmName("setStValValue")
        set(value) {
        _builder.stValValue = value
      }
    /**
     * ```
     * Value of the data.
     * ```
     *
     * `.commonmodule.SwitchingCapabilityKind stVal = 2 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];`
     */
    public fun clearStVal() {
      _builder.clearStVal()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun openfmb.commonmodule.ENS_SwitchingCapabilityKind.copy(block: `openfmb.commonmodule`.ENS_SwitchingCapabilityKindKt.Dsl.() -> kotlin.Unit): openfmb.commonmodule.ENS_SwitchingCapabilityKind =
  `openfmb.commonmodule`.ENS_SwitchingCapabilityKindKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val openfmb.commonmodule.ENS_SwitchingCapabilityKindOrBuilder.blkEnaOrNull: com.google.protobuf.BoolValue?
  get() = if (hasBlkEna()) getBlkEna() else null

