// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: commonmodule/commonmodule.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package openfmb.commonmodule;

@kotlin.jvm.JvmName("-initializeoperationDVAR")
public inline fun operationDVAR(block: openfmb.commonmodule.OperationDVARKt.Dsl.() -> kotlin.Unit): openfmb.commonmodule.OperationDVAR =
  openfmb.commonmodule.OperationDVARKt.Dsl._create(openfmb.commonmodule.OperationDVAR.newBuilder()).apply { block() }._build()
/**
 * ```
 * MISSING DOCUMENTATION!!!
 * ```
 *
 * Protobuf type `commonmodule.OperationDVAR`
 */
public object OperationDVARKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: openfmb.commonmodule.OperationDVAR.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: openfmb.commonmodule.OperationDVAR.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): openfmb.commonmodule.OperationDVAR = _builder.build()

    /**
     * ```
     * This is an absolute value field.  Constant Reactive Power
     * ```
     *
     * `float varTgtSpt = 1 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];`
     */
    public var varTgtSpt: kotlin.Float
      @JvmName("getVarTgtSpt")
      get() = _builder.getVarTgtSpt()
      @JvmName("setVarTgtSpt")
      set(value) {
        _builder.setVarTgtSpt(value)
      }
    /**
     * ```
     * This is an absolute value field.  Constant Reactive Power
     * ```
     *
     * `float varTgtSpt = 1 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];`
     */
    public fun clearVarTgtSpt() {
      _builder.clearVarTgtSpt()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun openfmb.commonmodule.OperationDVAR.copy(block: openfmb.commonmodule.OperationDVARKt.Dsl.() -> kotlin.Unit): openfmb.commonmodule.OperationDVAR =
  openfmb.commonmodule.OperationDVARKt.Dsl._create(this.toBuilder()).apply { block() }._build()

