//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: commonmodule/commonmodule.proto

package openfmb.commonmodule;

@kotlin.jvm.JvmName("-initializeoperationDWVR")
public inline fun operationDWVR(block: openfmb.commonmodule.OperationDWVRKt.Dsl.() -> kotlin.Unit): openfmb.commonmodule.OperationDWVR =
  openfmb.commonmodule.OperationDWVRKt.Dsl._create(openfmb.commonmodule.OperationDWVR.newBuilder()).apply { block() }._build()
public object OperationDWVRKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: openfmb.commonmodule.OperationDWVR.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: openfmb.commonmodule.OperationDWVR.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): openfmb.commonmodule.OperationDWVR = _builder.build()

    /**
     * <pre>
     * Active-Reactive Power Mode Enable
     * </pre>
     *
     * <code>bool modEna = 1 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public var modEna: kotlin.Boolean
      @JvmName("getModEna")
      get() = _builder.getModEna()
      @JvmName("setModEna")
      set(value) {
        _builder.setModEna(value)
      }
    /**
     * <pre>
     * Active-Reactive Power Mode Enable
     * </pre>
     *
     * <code>bool modEna = 1 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public fun clearModEna() {
      _builder.clearModEna()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun openfmb.commonmodule.OperationDWVR.copy(block: openfmb.commonmodule.OperationDWVRKt.Dsl.() -> kotlin.Unit): openfmb.commonmodule.OperationDWVR =
  openfmb.commonmodule.OperationDWVRKt.Dsl._create(this.toBuilder()).apply { block() }._build()

