// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: commonmodule/commonmodule.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package openfmb.commonmodule;

@kotlin.jvm.JvmName("-initializeoptionalPhaseFaultDirectionKind")
public inline fun optionalPhaseFaultDirectionKind(block: openfmb.commonmodule.Optional_PhaseFaultDirectionKindKt.Dsl.() -> kotlin.Unit): openfmb.commonmodule.Optional_PhaseFaultDirectionKind =
  openfmb.commonmodule.Optional_PhaseFaultDirectionKindKt.Dsl._create(openfmb.commonmodule.Optional_PhaseFaultDirectionKind.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `commonmodule.Optional_PhaseFaultDirectionKind`
 */
public object Optional_PhaseFaultDirectionKindKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: openfmb.commonmodule.Optional_PhaseFaultDirectionKind.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: openfmb.commonmodule.Optional_PhaseFaultDirectionKind.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): openfmb.commonmodule.Optional_PhaseFaultDirectionKind = _builder.build()

    /**
     * `.commonmodule.PhaseFaultDirectionKind value = 1;`
     */
    public var value: openfmb.commonmodule.PhaseFaultDirectionKind
      @kotlin.jvm.JvmName("getValue")
        get() = _builder.value
      @kotlin.jvm.JvmName("setValue")
        set(value) {
        _builder.value = value
      }
    public var valueValue: kotlin.Int
      @kotlin.jvm.JvmName("getValueValue")
        get() = _builder.valueValue
      @kotlin.jvm.JvmName("setValueValue")
        set(value) {
        _builder.valueValue = value
      }
    /**
     * `.commonmodule.PhaseFaultDirectionKind value = 1;`
     */
    public fun clearValue() {
      _builder.clearValue()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun openfmb.commonmodule.Optional_PhaseFaultDirectionKind.copy(block: `openfmb.commonmodule`.Optional_PhaseFaultDirectionKindKt.Dsl.() -> kotlin.Unit): openfmb.commonmodule.Optional_PhaseFaultDirectionKind =
  `openfmb.commonmodule`.Optional_PhaseFaultDirectionKindKt.Dsl._create(this.toBuilder()).apply { block() }._build()

