// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: commonmodule/commonmodule.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package openfmb.commonmodule;

@kotlin.jvm.JvmName("-initializephaseISC")
public inline fun phaseISC(block: openfmb.commonmodule.PhaseISCKt.Dsl.() -> kotlin.Unit): openfmb.commonmodule.PhaseISC =
  openfmb.commonmodule.PhaseISCKt.Dsl._create(openfmb.commonmodule.PhaseISC.newBuilder()).apply { block() }._build()
/**
 * ```
 * [OpenFMB CDC extension] Per Phase ISC.
 * ```
 *
 * Protobuf type `commonmodule.PhaseISC`
 */
public object PhaseISCKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: openfmb.commonmodule.PhaseISC.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: openfmb.commonmodule.PhaseISC.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): openfmb.commonmodule.PhaseISC = _builder.build()

    /**
     * ```
     * 3 Phase control.
     * ```
     *
     * `.commonmodule.ControlISC phs3 = 1;`
     */
    public var phs3: openfmb.commonmodule.ControlISC
      @JvmName("getPhs3")
      get() = _builder.getPhs3()
      @JvmName("setPhs3")
      set(value) {
        _builder.setPhs3(value)
      }
    /**
     * ```
     * 3 Phase control.
     * ```
     *
     * `.commonmodule.ControlISC phs3 = 1;`
     */
    public fun clearPhs3() {
      _builder.clearPhs3()
    }
    /**
     * ```
     * 3 Phase control.
     * ```
     *
     * `.commonmodule.ControlISC phs3 = 1;`
     * @return Whether the phs3 field is set.
     */
    public fun hasPhs3(): kotlin.Boolean {
      return _builder.hasPhs3()
    }

    /**
     * ```
     * Phase A control.
     * ```
     *
     * `.commonmodule.ControlISC phsA = 2;`
     */
    public var phsA: openfmb.commonmodule.ControlISC
      @JvmName("getPhsA")
      get() = _builder.getPhsA()
      @JvmName("setPhsA")
      set(value) {
        _builder.setPhsA(value)
      }
    /**
     * ```
     * Phase A control.
     * ```
     *
     * `.commonmodule.ControlISC phsA = 2;`
     */
    public fun clearPhsA() {
      _builder.clearPhsA()
    }
    /**
     * ```
     * Phase A control.
     * ```
     *
     * `.commonmodule.ControlISC phsA = 2;`
     * @return Whether the phsA field is set.
     */
    public fun hasPhsA(): kotlin.Boolean {
      return _builder.hasPhsA()
    }

    /**
     * ```
     * Phase B control.
     * ```
     *
     * `.commonmodule.ControlISC phsB = 3;`
     */
    public var phsB: openfmb.commonmodule.ControlISC
      @JvmName("getPhsB")
      get() = _builder.getPhsB()
      @JvmName("setPhsB")
      set(value) {
        _builder.setPhsB(value)
      }
    /**
     * ```
     * Phase B control.
     * ```
     *
     * `.commonmodule.ControlISC phsB = 3;`
     */
    public fun clearPhsB() {
      _builder.clearPhsB()
    }
    /**
     * ```
     * Phase B control.
     * ```
     *
     * `.commonmodule.ControlISC phsB = 3;`
     * @return Whether the phsB field is set.
     */
    public fun hasPhsB(): kotlin.Boolean {
      return _builder.hasPhsB()
    }

    /**
     * ```
     * Phase C control.
     * ```
     *
     * `.commonmodule.ControlISC phsC = 4;`
     */
    public var phsC: openfmb.commonmodule.ControlISC
      @JvmName("getPhsC")
      get() = _builder.getPhsC()
      @JvmName("setPhsC")
      set(value) {
        _builder.setPhsC(value)
      }
    /**
     * ```
     * Phase C control.
     * ```
     *
     * `.commonmodule.ControlISC phsC = 4;`
     */
    public fun clearPhsC() {
      _builder.clearPhsC()
    }
    /**
     * ```
     * Phase C control.
     * ```
     *
     * `.commonmodule.ControlISC phsC = 4;`
     * @return Whether the phsC field is set.
     */
    public fun hasPhsC(): kotlin.Boolean {
      return _builder.hasPhsC()
    }
  }
}
@kotlin.jvm.JvmSynthetic
@com.google.errorprone.annotations.CheckReturnValue
public inline fun openfmb.commonmodule.PhaseISC.copy(block: openfmb.commonmodule.PhaseISCKt.Dsl.() -> kotlin.Unit): openfmb.commonmodule.PhaseISC =
  openfmb.commonmodule.PhaseISCKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val openfmb.commonmodule.PhaseISCOrBuilder.phs3OrNull: openfmb.commonmodule.ControlISC?
  get() = if (hasPhs3()) getPhs3() else null

public val openfmb.commonmodule.PhaseISCOrBuilder.phsAOrNull: openfmb.commonmodule.ControlISC?
  get() = if (hasPhsA()) getPhsA() else null

public val openfmb.commonmodule.PhaseISCOrBuilder.phsBOrNull: openfmb.commonmodule.ControlISC?
  get() = if (hasPhsB()) getPhsB() else null

public val openfmb.commonmodule.PhaseISCOrBuilder.phsCOrNull: openfmb.commonmodule.ControlISC?
  get() = if (hasPhsC()) getPhsC() else null

