// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: commonmodule/commonmodule.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package openfmb.commonmodule;

@kotlin.jvm.JvmName("-initializepMG")
public inline fun pMG(block: openfmb.commonmodule.PMGKt.Dsl.() -> kotlin.Unit): openfmb.commonmodule.PMG =
  openfmb.commonmodule.PMGKt.Dsl._create(openfmb.commonmodule.PMG.newBuilder()).apply { block() }._build()
/**
 * ```
 * [OpenFMB CDC extension] Phase magnitude (PMG). Phase to ground/neutral related per-phase
 * measured values.
 * ```
 *
 * Protobuf type `commonmodule.PMG`
 */
public object PMGKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: openfmb.commonmodule.PMG.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: openfmb.commonmodule.PMG.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): openfmb.commonmodule.PMG = _builder.build()

    /**
     * ```
     * Net current, as the algebraic sum of the instantaneous values of currents flowing through all
     * live conductors and the neutral of a circuit at one point of the electrical installation ('phsA
     * instCVal'+'phsB.instCVal'+'phsC.instCVal'+'neut.instCVal').
     * ```
     *
     * `.commonmodule.MV net = 1;`
     */
    public var net: openfmb.commonmodule.MV
      @kotlin.jvm.JvmName("getNet")
        get() = _builder.net
      @kotlin.jvm.JvmName("setNet")
        set(value) {
        _builder.net = value
      }
    /**
     * ```
     * Net current, as the algebraic sum of the instantaneous values of currents flowing through all
     * live conductors and the neutral of a circuit at one point of the electrical installation ('phsA
     * instCVal'+'phsB.instCVal'+'phsC.instCVal'+'neut.instCVal').
     * ```
     *
     * `.commonmodule.MV net = 1;`
     */
    public fun clearNet() {
      _builder.clearNet()
    }
    /**
     * ```
     * Net current, as the algebraic sum of the instantaneous values of currents flowing through all
     * live conductors and the neutral of a circuit at one point of the electrical installation ('phsA
     * instCVal'+'phsB.instCVal'+'phsC.instCVal'+'neut.instCVal').
     * ```
     *
     * `.commonmodule.MV net = 1;`
     * @return Whether the net field is set.
     */
    public fun hasNet(): kotlin.Boolean {
      return _builder.hasNet()
    }

    public val PMGKt.Dsl.netOrNull: openfmb.commonmodule.MV?
      get() = _builder.netOrNull

    /**
     * ```
     * Value of phase A.
     * ```
     *
     * `.commonmodule.MV phsA = 2;`
     */
    public var phsA: openfmb.commonmodule.MV
      @kotlin.jvm.JvmName("getPhsA")
        get() = _builder.phsA
      @kotlin.jvm.JvmName("setPhsA")
        set(value) {
        _builder.phsA = value
      }
    /**
     * ```
     * Value of phase A.
     * ```
     *
     * `.commonmodule.MV phsA = 2;`
     */
    public fun clearPhsA() {
      _builder.clearPhsA()
    }
    /**
     * ```
     * Value of phase A.
     * ```
     *
     * `.commonmodule.MV phsA = 2;`
     * @return Whether the phsA field is set.
     */
    public fun hasPhsA(): kotlin.Boolean {
      return _builder.hasPhsA()
    }

    public val PMGKt.Dsl.phsAOrNull: openfmb.commonmodule.MV?
      get() = _builder.phsAOrNull

    /**
     * ```
     * Value of phase B.
     * ```
     *
     * `.commonmodule.MV phsB = 3;`
     */
    public var phsB: openfmb.commonmodule.MV
      @kotlin.jvm.JvmName("getPhsB")
        get() = _builder.phsB
      @kotlin.jvm.JvmName("setPhsB")
        set(value) {
        _builder.phsB = value
      }
    /**
     * ```
     * Value of phase B.
     * ```
     *
     * `.commonmodule.MV phsB = 3;`
     */
    public fun clearPhsB() {
      _builder.clearPhsB()
    }
    /**
     * ```
     * Value of phase B.
     * ```
     *
     * `.commonmodule.MV phsB = 3;`
     * @return Whether the phsB field is set.
     */
    public fun hasPhsB(): kotlin.Boolean {
      return _builder.hasPhsB()
    }

    public val PMGKt.Dsl.phsBOrNull: openfmb.commonmodule.MV?
      get() = _builder.phsBOrNull

    /**
     * ```
     * Value of phase C.
     * ```
     *
     * `.commonmodule.MV phsC = 4;`
     */
    public var phsC: openfmb.commonmodule.MV
      @kotlin.jvm.JvmName("getPhsC")
        get() = _builder.phsC
      @kotlin.jvm.JvmName("setPhsC")
        set(value) {
        _builder.phsC = value
      }
    /**
     * ```
     * Value of phase C.
     * ```
     *
     * `.commonmodule.MV phsC = 4;`
     */
    public fun clearPhsC() {
      _builder.clearPhsC()
    }
    /**
     * ```
     * Value of phase C.
     * ```
     *
     * `.commonmodule.MV phsC = 4;`
     * @return Whether the phsC field is set.
     */
    public fun hasPhsC(): kotlin.Boolean {
      return _builder.hasPhsC()
    }

    public val PMGKt.Dsl.phsCOrNull: openfmb.commonmodule.MV?
      get() = _builder.phsCOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun openfmb.commonmodule.PMG.copy(block: `openfmb.commonmodule`.PMGKt.Dsl.() -> kotlin.Unit): openfmb.commonmodule.PMG =
  `openfmb.commonmodule`.PMGKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val openfmb.commonmodule.PMGOrBuilder.netOrNull: openfmb.commonmodule.MV?
  get() = if (hasNet()) getNet() else null

public val openfmb.commonmodule.PMGOrBuilder.phsAOrNull: openfmb.commonmodule.MV?
  get() = if (hasPhsA()) getPhsA() else null

public val openfmb.commonmodule.PMGOrBuilder.phsBOrNull: openfmb.commonmodule.MV?
  get() = if (hasPhsB()) getPhsB() else null

public val openfmb.commonmodule.PMGOrBuilder.phsCOrNull: openfmb.commonmodule.MV?
  get() = if (hasPhsC()) getPhsC() else null

