//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: commonmodule/commonmodule.proto

package openfmb.commonmodule;

@kotlin.jvm.JvmName("-initializesourceCapabilityRatings")
public inline fun sourceCapabilityRatings(block: openfmb.commonmodule.SourceCapabilityRatingsKt.Dsl.() -> kotlin.Unit): openfmb.commonmodule.SourceCapabilityRatings =
  openfmb.commonmodule.SourceCapabilityRatingsKt.Dsl._create(openfmb.commonmodule.SourceCapabilityRatings.newBuilder()).apply { block() }._build()
public object SourceCapabilityRatingsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: openfmb.commonmodule.SourceCapabilityRatings.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: openfmb.commonmodule.SourceCapabilityRatings.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): openfmb.commonmodule.SourceCapabilityRatings = _builder.build()

    /**
     * <pre>
     * UML inherited base object
     * </pre>
     *
     * <code>.commonmodule.LogicalNode logicalNode = 1 [(.uml.option_parent_message) = true];</code>
     */
    public var logicalNode: openfmb.commonmodule.LogicalNode
      @JvmName("getLogicalNode")
      get() = _builder.getLogicalNode()
      @JvmName("setLogicalNode")
      set(value) {
        _builder.setLogicalNode(value)
      }
    /**
     * <pre>
     * UML inherited base object
     * </pre>
     *
     * <code>.commonmodule.LogicalNode logicalNode = 1 [(.uml.option_parent_message) = true];</code>
     */
    public fun clearLogicalNode() {
      _builder.clearLogicalNode()
    }
    /**
     * <pre>
     * UML inherited base object
     * </pre>
     *
     * <code>.commonmodule.LogicalNode logicalNode = 1 [(.uml.option_parent_message) = true];</code>
     * @return Whether the logicalNode field is set.
     */
    public fun hasLogicalNode(): kotlin.Boolean {
      return _builder.hasLogicalNode()
    }

    /**
     * <pre>
     * Abnormal Operating Performance Category  Text stating: “IEEE 1547:2018 Either “I”, “II”, or
     * “III” is stated for the Abnormal Category
     * </pre>
     *
     * <code>.commonmodule.AbnOpCatKind AbnOpCatRtg = 2 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public var abnOpCatRtg: openfmb.commonmodule.AbnOpCatKind
      @JvmName("getAbnOpCatRtg")
      get() = _builder.getAbnOpCatRtg()
      @JvmName("setAbnOpCatRtg")
      set(value) {
        _builder.setAbnOpCatRtg(value)
      }
    /**
     * <pre>
     * Abnormal Operating Performance Category  Text stating: “IEEE 1547:2018 Either “I”, “II”, or
     * “III” is stated for the Abnormal Category
     * </pre>
     *
     * <code>.commonmodule.AbnOpCatKind AbnOpCatRtg = 2 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public fun clearAbnOpCatRtg() {
      _builder.clearAbnOpCatRtg()
    }

    /**
     * <pre>
     * Amp Maximum Rating  SunSpec has this field but not in IEEE1547
     * </pre>
     *
     * <code>.commonmodule.ASG AMaxRtg = 3;</code>
     */
    public var aMaxRtg: openfmb.commonmodule.ASG
      @JvmName("getAMaxRtg")
      get() = _builder.getAMaxRtg()
      @JvmName("setAMaxRtg")
      set(value) {
        _builder.setAMaxRtg(value)
      }
    /**
     * <pre>
     * Amp Maximum Rating  SunSpec has this field but not in IEEE1547
     * </pre>
     *
     * <code>.commonmodule.ASG AMaxRtg = 3;</code>
     */
    public fun clearAMaxRtg() {
      _builder.clearAMaxRtg()
    }
    /**
     * <pre>
     * Amp Maximum Rating  SunSpec has this field but not in IEEE1547
     * </pre>
     *
     * <code>.commonmodule.ASG AMaxRtg = 3;</code>
     * @return Whether the aMaxRtg field is set.
     */
    public fun hasAMaxRtg(): kotlin.Boolean {
      return _builder.hasAMaxRtg()
    }

    /**
     * <pre>
     * Frequency nominal rating, default to 60 hz if not provide and cannot be configured.
     * </pre>
     *
     * <code>.commonmodule.ASG FreqNomRtg = 4 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public var freqNomRtg: openfmb.commonmodule.ASG
      @JvmName("getFreqNomRtg")
      get() = _builder.getFreqNomRtg()
      @JvmName("setFreqNomRtg")
      set(value) {
        _builder.setFreqNomRtg(value)
      }
    /**
     * <pre>
     * Frequency nominal rating, default to 60 hz if not provide and cannot be configured.
     * </pre>
     *
     * <code>.commonmodule.ASG FreqNomRtg = 4 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public fun clearFreqNomRtg() {
      _builder.clearFreqNomRtg()
    }
    /**
     * <pre>
     * Frequency nominal rating, default to 60 hz if not provide and cannot be configured.
     * </pre>
     *
     * <code>.commonmodule.ASG FreqNomRtg = 4 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     * @return Whether the freqNomRtg field is set.
     */
    public fun hasFreqNomRtg(): kotlin.Boolean {
      return _builder.hasFreqNomRtg()
    }

    /**
     * <pre>
     * Normal operating performance category
     * </pre>
     *
     * <code>.commonmodule.NorOpCatKind NorOpCatRtg = 5 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public var norOpCatRtg: openfmb.commonmodule.NorOpCatKind
      @JvmName("getNorOpCatRtg")
      get() = _builder.getNorOpCatRtg()
      @JvmName("setNorOpCatRtg")
      set(value) {
        _builder.setNorOpCatRtg(value)
      }
    /**
     * <pre>
     * Normal operating performance category
     * </pre>
     *
     * <code>.commonmodule.NorOpCatKind NorOpCatRtg = 5 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public fun clearNorOpCatRtg() {
      _builder.clearNorOpCatRtg()
    }

    /**
     * <pre>
     * Reactive susceptance that remains connected to the Area EPS in the cease to energize and trip state
     * </pre>
     *
     * <code>.commonmodule.ASG ReactSusceptRtg = 6 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public var reactSusceptRtg: openfmb.commonmodule.ASG
      @JvmName("getReactSusceptRtg")
      get() = _builder.getReactSusceptRtg()
      @JvmName("setReactSusceptRtg")
      set(value) {
        _builder.setReactSusceptRtg(value)
      }
    /**
     * <pre>
     * Reactive susceptance that remains connected to the Area EPS in the cease to energize and trip state
     * </pre>
     *
     * <code>.commonmodule.ASG ReactSusceptRtg = 6 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public fun clearReactSusceptRtg() {
      _builder.clearReactSusceptRtg()
    }
    /**
     * <pre>
     * Reactive susceptance that remains connected to the Area EPS in the cease to energize and trip state
     * </pre>
     *
     * <code>.commonmodule.ASG ReactSusceptRtg = 6 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     * @return Whether the reactSusceptRtg field is set.
     */
    public fun hasReactSusceptRtg(): kotlin.Boolean {
      return _builder.hasReactSusceptRtg()
    }

    /**
     * <pre>
     * Apparent Power Maximum Rating
     * </pre>
     *
     * <code>.commonmodule.ASG VAMaxRtg = 7 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public var vAMaxRtg: openfmb.commonmodule.ASG
      @JvmName("getVAMaxRtg")
      get() = _builder.getVAMaxRtg()
      @JvmName("setVAMaxRtg")
      set(value) {
        _builder.setVAMaxRtg(value)
      }
    /**
     * <pre>
     * Apparent Power Maximum Rating
     * </pre>
     *
     * <code>.commonmodule.ASG VAMaxRtg = 7 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public fun clearVAMaxRtg() {
      _builder.clearVAMaxRtg()
    }
    /**
     * <pre>
     * Apparent Power Maximum Rating
     * </pre>
     *
     * <code>.commonmodule.ASG VAMaxRtg = 7 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     * @return Whether the vAMaxRtg field is set.
     */
    public fun hasVAMaxRtg(): kotlin.Boolean {
      return _builder.hasVAMaxRtg()
    }

    /**
     * <pre>
     * Reactive Power Absorbed Maximum Rating
     * </pre>
     *
     * <code>.commonmodule.ASG VarMaxAbsRtg = 8 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public var varMaxAbsRtg: openfmb.commonmodule.ASG
      @JvmName("getVarMaxAbsRtg")
      get() = _builder.getVarMaxAbsRtg()
      @JvmName("setVarMaxAbsRtg")
      set(value) {
        _builder.setVarMaxAbsRtg(value)
      }
    /**
     * <pre>
     * Reactive Power Absorbed Maximum Rating
     * </pre>
     *
     * <code>.commonmodule.ASG VarMaxAbsRtg = 8 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public fun clearVarMaxAbsRtg() {
      _builder.clearVarMaxAbsRtg()
    }
    /**
     * <pre>
     * Reactive Power Absorbed Maximum Rating
     * </pre>
     *
     * <code>.commonmodule.ASG VarMaxAbsRtg = 8 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     * @return Whether the varMaxAbsRtg field is set.
     */
    public fun hasVarMaxAbsRtg(): kotlin.Boolean {
      return _builder.hasVarMaxAbsRtg()
    }

    /**
     * <pre>
     * Reactive Power Injected Maximum Rating
     * </pre>
     *
     * <code>.commonmodule.ASG VarMaxInjRtg = 9 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public var varMaxInjRtg: openfmb.commonmodule.ASG
      @JvmName("getVarMaxInjRtg")
      get() = _builder.getVarMaxInjRtg()
      @JvmName("setVarMaxInjRtg")
      set(value) {
        _builder.setVarMaxInjRtg(value)
      }
    /**
     * <pre>
     * Reactive Power Injected Maximum Rating
     * </pre>
     *
     * <code>.commonmodule.ASG VarMaxInjRtg = 9 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public fun clearVarMaxInjRtg() {
      _builder.clearVarMaxInjRtg()
    }
    /**
     * <pre>
     * Reactive Power Injected Maximum Rating
     * </pre>
     *
     * <code>.commonmodule.ASG VarMaxInjRtg = 9 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     * @return Whether the varMaxInjRtg field is set.
     */
    public fun hasVarMaxInjRtg(): kotlin.Boolean {
      return _builder.hasVarMaxInjRtg()
    }

    /**
     * <pre>
     * AC voltage maximum rating
     * </pre>
     *
     * <code>.commonmodule.ASG VMaxRtg = 10 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public var vMaxRtg: openfmb.commonmodule.ASG
      @JvmName("getVMaxRtg")
      get() = _builder.getVMaxRtg()
      @JvmName("setVMaxRtg")
      set(value) {
        _builder.setVMaxRtg(value)
      }
    /**
     * <pre>
     * AC voltage maximum rating
     * </pre>
     *
     * <code>.commonmodule.ASG VMaxRtg = 10 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public fun clearVMaxRtg() {
      _builder.clearVMaxRtg()
    }
    /**
     * <pre>
     * AC voltage maximum rating
     * </pre>
     *
     * <code>.commonmodule.ASG VMaxRtg = 10 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     * @return Whether the vMaxRtg field is set.
     */
    public fun hasVMaxRtg(): kotlin.Boolean {
      return _builder.hasVMaxRtg()
    }

    /**
     * <pre>
     * AC voltage minimum rating
     * </pre>
     *
     * <code>.commonmodule.ASG VMinRtg = 11 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public var vMinRtg: openfmb.commonmodule.ASG
      @JvmName("getVMinRtg")
      get() = _builder.getVMinRtg()
      @JvmName("setVMinRtg")
      set(value) {
        _builder.setVMinRtg(value)
      }
    /**
     * <pre>
     * AC voltage minimum rating
     * </pre>
     *
     * <code>.commonmodule.ASG VMinRtg = 11 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public fun clearVMinRtg() {
      _builder.clearVMinRtg()
    }
    /**
     * <pre>
     * AC voltage minimum rating
     * </pre>
     *
     * <code>.commonmodule.ASG VMinRtg = 11 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     * @return Whether the vMinRtg field is set.
     */
    public fun hasVMinRtg(): kotlin.Boolean {
      return _builder.hasVMinRtg()
    }

    /**
     * <pre>
     * AC voltage nominal rating
     * </pre>
     *
     * <code>.commonmodule.ASG VNomRtg = 12 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public var vNomRtg: openfmb.commonmodule.ASG
      @JvmName("getVNomRtg")
      get() = _builder.getVNomRtg()
      @JvmName("setVNomRtg")
      set(value) {
        _builder.setVNomRtg(value)
      }
    /**
     * <pre>
     * AC voltage nominal rating
     * </pre>
     *
     * <code>.commonmodule.ASG VNomRtg = 12 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public fun clearVNomRtg() {
      _builder.clearVNomRtg()
    }
    /**
     * <pre>
     * AC voltage nominal rating
     * </pre>
     *
     * <code>.commonmodule.ASG VNomRtg = 12 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     * @return Whether the vNomRtg field is set.
     */
    public fun hasVNomRtg(): kotlin.Boolean {
      return _builder.hasVNomRtg()
    }

    /**
     * <pre>
     * Active Power Max Rating
     * </pre>
     *
     * <code>.commonmodule.ASG WMaxRtg = 13 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public var wMaxRtg: openfmb.commonmodule.ASG
      @JvmName("getWMaxRtg")
      get() = _builder.getWMaxRtg()
      @JvmName("setWMaxRtg")
      set(value) {
        _builder.setWMaxRtg(value)
      }
    /**
     * <pre>
     * Active Power Max Rating
     * </pre>
     *
     * <code>.commonmodule.ASG WMaxRtg = 13 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public fun clearWMaxRtg() {
      _builder.clearWMaxRtg()
    }
    /**
     * <pre>
     * Active Power Max Rating
     * </pre>
     *
     * <code>.commonmodule.ASG WMaxRtg = 13 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     * @return Whether the wMaxRtg field is set.
     */
    public fun hasWMaxRtg(): kotlin.Boolean {
      return _builder.hasWMaxRtg()
    }

    /**
     * <pre>
     * Active Power (Over-Excited) Rating
     * </pre>
     *
     * <code>.commonmodule.ASG WOvrExtRtg = 14 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public var wOvrExtRtg: openfmb.commonmodule.ASG
      @JvmName("getWOvrExtRtg")
      get() = _builder.getWOvrExtRtg()
      @JvmName("setWOvrExtRtg")
      set(value) {
        _builder.setWOvrExtRtg(value)
      }
    /**
     * <pre>
     * Active Power (Over-Excited) Rating
     * </pre>
     *
     * <code>.commonmodule.ASG WOvrExtRtg = 14 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public fun clearWOvrExtRtg() {
      _builder.clearWOvrExtRtg()
    }
    /**
     * <pre>
     * Active Power (Over-Excited) Rating
     * </pre>
     *
     * <code>.commonmodule.ASG WOvrExtRtg = 14 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     * @return Whether the wOvrExtRtg field is set.
     */
    public fun hasWOvrExtRtg(): kotlin.Boolean {
      return _builder.hasWOvrExtRtg()
    }

    /**
     * <pre>
     * Active power rating at specified over-excited power factor
     * </pre>
     *
     * <code>.commonmodule.ASG WOvrExtRtgPF = 15 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public var wOvrExtRtgPF: openfmb.commonmodule.ASG
      @JvmName("getWOvrExtRtgPF")
      get() = _builder.getWOvrExtRtgPF()
      @JvmName("setWOvrExtRtgPF")
      set(value) {
        _builder.setWOvrExtRtgPF(value)
      }
    /**
     * <pre>
     * Active power rating at specified over-excited power factor
     * </pre>
     *
     * <code>.commonmodule.ASG WOvrExtRtgPF = 15 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public fun clearWOvrExtRtgPF() {
      _builder.clearWOvrExtRtgPF()
    }
    /**
     * <pre>
     * Active power rating at specified over-excited power factor
     * </pre>
     *
     * <code>.commonmodule.ASG WOvrExtRtgPF = 15 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     * @return Whether the wOvrExtRtgPF field is set.
     */
    public fun hasWOvrExtRtgPF(): kotlin.Boolean {
      return _builder.hasWOvrExtRtgPF()
    }

    /**
     * <pre>
     * Active Power (Under-Excited) Rating
     * </pre>
     *
     * <code>.commonmodule.ASG WUndExtRtg = 16 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public var wUndExtRtg: openfmb.commonmodule.ASG
      @JvmName("getWUndExtRtg")
      get() = _builder.getWUndExtRtg()
      @JvmName("setWUndExtRtg")
      set(value) {
        _builder.setWUndExtRtg(value)
      }
    /**
     * <pre>
     * Active Power (Under-Excited) Rating
     * </pre>
     *
     * <code>.commonmodule.ASG WUndExtRtg = 16 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public fun clearWUndExtRtg() {
      _builder.clearWUndExtRtg()
    }
    /**
     * <pre>
     * Active Power (Under-Excited) Rating
     * </pre>
     *
     * <code>.commonmodule.ASG WUndExtRtg = 16 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     * @return Whether the wUndExtRtg field is set.
     */
    public fun hasWUndExtRtg(): kotlin.Boolean {
      return _builder.hasWUndExtRtg()
    }

    /**
     * <pre>
     * Active power rating at specified under-excited power factor
     * </pre>
     *
     * <code>.commonmodule.ASG WUndExtRtgPF = 17 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public var wUndExtRtgPF: openfmb.commonmodule.ASG
      @JvmName("getWUndExtRtgPF")
      get() = _builder.getWUndExtRtgPF()
      @JvmName("setWUndExtRtgPF")
      set(value) {
        _builder.setWUndExtRtgPF(value)
      }
    /**
     * <pre>
     * Active power rating at specified under-excited power factor
     * </pre>
     *
     * <code>.commonmodule.ASG WUndExtRtgPF = 17 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public fun clearWUndExtRtgPF() {
      _builder.clearWUndExtRtgPF()
    }
    /**
     * <pre>
     * Active power rating at specified under-excited power factor
     * </pre>
     *
     * <code>.commonmodule.ASG WUndExtRtgPF = 17 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     * @return Whether the wUndExtRtgPF field is set.
     */
    public fun hasWUndExtRtgPF(): kotlin.Boolean {
      return _builder.hasWUndExtRtgPF()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun openfmb.commonmodule.SourceCapabilityRatings.copy(block: openfmb.commonmodule.SourceCapabilityRatingsKt.Dsl.() -> kotlin.Unit): openfmb.commonmodule.SourceCapabilityRatings =
  openfmb.commonmodule.SourceCapabilityRatingsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val openfmb.commonmodule.SourceCapabilityRatingsOrBuilder.logicalNodeOrNull: openfmb.commonmodule.LogicalNode?
  get() = if (hasLogicalNode()) getLogicalNode() else null

public val openfmb.commonmodule.SourceCapabilityRatingsOrBuilder.aMaxRtgOrNull: openfmb.commonmodule.ASG?
  get() = if (hasAMaxRtg()) getAMaxRtg() else null

public val openfmb.commonmodule.SourceCapabilityRatingsOrBuilder.freqNomRtgOrNull: openfmb.commonmodule.ASG?
  get() = if (hasFreqNomRtg()) getFreqNomRtg() else null

public val openfmb.commonmodule.SourceCapabilityRatingsOrBuilder.reactSusceptRtgOrNull: openfmb.commonmodule.ASG?
  get() = if (hasReactSusceptRtg()) getReactSusceptRtg() else null

public val openfmb.commonmodule.SourceCapabilityRatingsOrBuilder.vAMaxRtgOrNull: openfmb.commonmodule.ASG?
  get() = if (hasVAMaxRtg()) getVAMaxRtg() else null

public val openfmb.commonmodule.SourceCapabilityRatingsOrBuilder.varMaxAbsRtgOrNull: openfmb.commonmodule.ASG?
  get() = if (hasVarMaxAbsRtg()) getVarMaxAbsRtg() else null

public val openfmb.commonmodule.SourceCapabilityRatingsOrBuilder.varMaxInjRtgOrNull: openfmb.commonmodule.ASG?
  get() = if (hasVarMaxInjRtg()) getVarMaxInjRtg() else null

public val openfmb.commonmodule.SourceCapabilityRatingsOrBuilder.vMaxRtgOrNull: openfmb.commonmodule.ASG?
  get() = if (hasVMaxRtg()) getVMaxRtg() else null

public val openfmb.commonmodule.SourceCapabilityRatingsOrBuilder.vMinRtgOrNull: openfmb.commonmodule.ASG?
  get() = if (hasVMinRtg()) getVMinRtg() else null

public val openfmb.commonmodule.SourceCapabilityRatingsOrBuilder.vNomRtgOrNull: openfmb.commonmodule.ASG?
  get() = if (hasVNomRtg()) getVNomRtg() else null

public val openfmb.commonmodule.SourceCapabilityRatingsOrBuilder.wMaxRtgOrNull: openfmb.commonmodule.ASG?
  get() = if (hasWMaxRtg()) getWMaxRtg() else null

public val openfmb.commonmodule.SourceCapabilityRatingsOrBuilder.wOvrExtRtgOrNull: openfmb.commonmodule.ASG?
  get() = if (hasWOvrExtRtg()) getWOvrExtRtg() else null

public val openfmb.commonmodule.SourceCapabilityRatingsOrBuilder.wOvrExtRtgPFOrNull: openfmb.commonmodule.ASG?
  get() = if (hasWOvrExtRtgPF()) getWOvrExtRtgPF() else null

public val openfmb.commonmodule.SourceCapabilityRatingsOrBuilder.wUndExtRtgOrNull: openfmb.commonmodule.ASG?
  get() = if (hasWUndExtRtg()) getWUndExtRtg() else null

public val openfmb.commonmodule.SourceCapabilityRatingsOrBuilder.wUndExtRtgPFOrNull: openfmb.commonmodule.ASG?
  get() = if (hasWUndExtRtgPF()) getWUndExtRtgPF() else null

