//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: commonmodule/commonmodule.proto

package openfmb.commonmodule;

@kotlin.jvm.JvmName("-initializestatusSPS")
public inline fun statusSPS(block: openfmb.commonmodule.StatusSPSKt.Dsl.() -> kotlin.Unit): openfmb.commonmodule.StatusSPS =
  openfmb.commonmodule.StatusSPSKt.Dsl._create(openfmb.commonmodule.StatusSPS.newBuilder()).apply { block() }._build()
public object StatusSPSKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: openfmb.commonmodule.StatusSPS.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: openfmb.commonmodule.StatusSPS.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): openfmb.commonmodule.StatusSPS = _builder.build()

    /**
     * <pre>
     * MISSING DOCUMENTATION!!!
     * </pre>
     *
     * <code>.commonmodule.Quality q = 1;</code>
     */
    public var q: openfmb.commonmodule.Quality
      @JvmName("getQ")
      get() = _builder.getQ()
      @JvmName("setQ")
      set(value) {
        _builder.setQ(value)
      }
    /**
     * <pre>
     * MISSING DOCUMENTATION!!!
     * </pre>
     *
     * <code>.commonmodule.Quality q = 1;</code>
     */
    public fun clearQ() {
      _builder.clearQ()
    }
    /**
     * <pre>
     * MISSING DOCUMENTATION!!!
     * </pre>
     *
     * <code>.commonmodule.Quality q = 1;</code>
     * @return Whether the q field is set.
     */
    public fun hasQ(): kotlin.Boolean {
      return _builder.hasQ()
    }

    /**
     * <pre>
     * MISSING DOCUMENTATION!!!
     * </pre>
     *
     * <code>bool stVal = 2 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public var stVal: kotlin.Boolean
      @JvmName("getStVal")
      get() = _builder.getStVal()
      @JvmName("setStVal")
      set(value) {
        _builder.setStVal(value)
      }
    /**
     * <pre>
     * MISSING DOCUMENTATION!!!
     * </pre>
     *
     * <code>bool stVal = 2 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public fun clearStVal() {
      _builder.clearStVal()
    }

    /**
     * <pre>
     * MISSING DOCUMENTATION!!!
     * </pre>
     *
     * <code>.commonmodule.Timestamp t = 3;</code>
     */
    public var t: openfmb.commonmodule.Timestamp
      @JvmName("getT")
      get() = _builder.getT()
      @JvmName("setT")
      set(value) {
        _builder.setT(value)
      }
    /**
     * <pre>
     * MISSING DOCUMENTATION!!!
     * </pre>
     *
     * <code>.commonmodule.Timestamp t = 3;</code>
     */
    public fun clearT() {
      _builder.clearT()
    }
    /**
     * <pre>
     * MISSING DOCUMENTATION!!!
     * </pre>
     *
     * <code>.commonmodule.Timestamp t = 3;</code>
     * @return Whether the t field is set.
     */
    public fun hasT(): kotlin.Boolean {
      return _builder.hasT()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun openfmb.commonmodule.StatusSPS.copy(block: openfmb.commonmodule.StatusSPSKt.Dsl.() -> kotlin.Unit): openfmb.commonmodule.StatusSPS =
  openfmb.commonmodule.StatusSPSKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val openfmb.commonmodule.StatusSPSOrBuilder.qOrNull: openfmb.commonmodule.Quality?
  get() = if (hasQ()) getQ() else null

public val openfmb.commonmodule.StatusSPSOrBuilder.tOrNull: openfmb.commonmodule.Timestamp?
  get() = if (hasT()) getT() else null

