// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: commonmodule/commonmodule.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package openfmb.commonmodule;

@kotlin.jvm.JvmName("-initializetmHzPoint")
public inline fun tmHzPoint(block: openfmb.commonmodule.TmHzPointKt.Dsl.() -> kotlin.Unit): openfmb.commonmodule.TmHzPoint =
  openfmb.commonmodule.TmHzPointKt.Dsl._create(openfmb.commonmodule.TmHzPoint.newBuilder()).apply { block() }._build()
/**
 * ```
 * MISSING DOCUMENTATION!!!
 * ```
 *
 * Protobuf type `commonmodule.TmHzPoint`
 */
public object TmHzPointKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: openfmb.commonmodule.TmHzPoint.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: openfmb.commonmodule.TmHzPoint.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): openfmb.commonmodule.TmHzPoint = _builder.build()

    /**
     * ```
     * This is an absolute value field.
     * ```
     *
     * `float hzVal = 1 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];`
     */
    public var hzVal: kotlin.Float
      @JvmName("getHzVal")
      get() = _builder.getHzVal()
      @JvmName("setHzVal")
      set(value) {
        _builder.setHzVal(value)
      }
    /**
     * ```
     * This is an absolute value field.
     * ```
     *
     * `float hzVal = 1 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];`
     */
    public fun clearHzVal() {
      _builder.clearHzVal()
    }

    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.ClearingTime tmVal = 2 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];`
     */
    public var tmVal: openfmb.commonmodule.ClearingTime
      @JvmName("getTmVal")
      get() = _builder.getTmVal()
      @JvmName("setTmVal")
      set(value) {
        _builder.setTmVal(value)
      }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.ClearingTime tmVal = 2 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];`
     */
    public fun clearTmVal() {
      _builder.clearTmVal()
    }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.ClearingTime tmVal = 2 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];`
     * @return Whether the tmVal field is set.
     */
    public fun hasTmVal(): kotlin.Boolean {
      return _builder.hasTmVal()
    }
  }
}
@kotlin.jvm.JvmSynthetic
@com.google.errorprone.annotations.CheckReturnValue
public inline fun openfmb.commonmodule.TmHzPoint.copy(block: openfmb.commonmodule.TmHzPointKt.Dsl.() -> kotlin.Unit): openfmb.commonmodule.TmHzPoint =
  openfmb.commonmodule.TmHzPointKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val openfmb.commonmodule.TmHzPointOrBuilder.tmValOrNull: openfmb.commonmodule.ClearingTime?
  get() = if (hasTmVal()) getTmVal() else null

