//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: commonmodule/commonmodule.proto

package openfmb.commonmodule;

@kotlin.jvm.JvmName("-initializevoltVarPoint")
public inline fun voltVarPoint(block: openfmb.commonmodule.VoltVarPointKt.Dsl.() -> kotlin.Unit): openfmb.commonmodule.VoltVarPoint =
  openfmb.commonmodule.VoltVarPointKt.Dsl._create(openfmb.commonmodule.VoltVarPoint.newBuilder()).apply { block() }._build()
public object VoltVarPointKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: openfmb.commonmodule.VoltVarPoint.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: openfmb.commonmodule.VoltVarPoint.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): openfmb.commonmodule.VoltVarPoint = _builder.build()

    /**
     * <pre>
     * This is an absolute value field.
     * </pre>
     *
     * <code>float varVal = 1 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public var varVal: kotlin.Float
      @JvmName("getVarVal")
      get() = _builder.getVarVal()
      @JvmName("setVarVal")
      set(value) {
        _builder.setVarVal(value)
      }
    /**
     * <pre>
     * This is an absolute value field.
     * </pre>
     *
     * <code>float varVal = 1 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public fun clearVarVal() {
      _builder.clearVarVal()
    }

    /**
     * <pre>
     * This is an absolute value field.
     * </pre>
     *
     * <code>float voltVal = 2 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public var voltVal: kotlin.Float
      @JvmName("getVoltVal")
      get() = _builder.getVoltVal()
      @JvmName("setVoltVal")
      set(value) {
        _builder.setVoltVal(value)
      }
    /**
     * <pre>
     * This is an absolute value field.
     * </pre>
     *
     * <code>float voltVal = 2 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public fun clearVoltVal() {
      _builder.clearVoltVal()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun openfmb.commonmodule.VoltVarPoint.copy(block: openfmb.commonmodule.VoltVarPointKt.Dsl.() -> kotlin.Unit): openfmb.commonmodule.VoltVarPoint =
  openfmb.commonmodule.VoltVarPointKt.Dsl._create(this.toBuilder()).apply { block() }._build()

