//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: solarmodule/solarmodule.proto

package openfmb.solarmodule;

@kotlin.jvm.JvmName("-initializesolarEventZGEN")
public inline fun solarEventZGEN(block: openfmb.solarmodule.SolarEventZGENKt.Dsl.() -> kotlin.Unit): openfmb.solarmodule.SolarEventZGEN =
  openfmb.solarmodule.SolarEventZGENKt.Dsl._create(openfmb.solarmodule.SolarEventZGEN.newBuilder()).apply { block() }._build()
public object SolarEventZGENKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: openfmb.solarmodule.SolarEventZGEN.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: openfmb.solarmodule.SolarEventZGEN.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): openfmb.solarmodule.SolarEventZGEN = _builder.build()

    /**
     * <pre>
     * UML inherited base object
     * </pre>
     *
     * <code>.solarmodule.SolarEventAndStatusZGEN solarEventAndStatusZGEN = 1 [(.uml.option_parent_message) = true];</code>
     */
    public var solarEventAndStatusZGEN: openfmb.solarmodule.SolarEventAndStatusZGEN
      @JvmName("getSolarEventAndStatusZGEN")
      get() = _builder.getSolarEventAndStatusZGEN()
      @JvmName("setSolarEventAndStatusZGEN")
      set(value) {
        _builder.setSolarEventAndStatusZGEN(value)
      }
    /**
     * <pre>
     * UML inherited base object
     * </pre>
     *
     * <code>.solarmodule.SolarEventAndStatusZGEN solarEventAndStatusZGEN = 1 [(.uml.option_parent_message) = true];</code>
     */
    public fun clearSolarEventAndStatusZGEN() {
      _builder.clearSolarEventAndStatusZGEN()
    }
    /**
     * <pre>
     * UML inherited base object
     * </pre>
     *
     * <code>.solarmodule.SolarEventAndStatusZGEN solarEventAndStatusZGEN = 1 [(.uml.option_parent_message) = true];</code>
     * @return Whether the solarEventAndStatusZGEN field is set.
     */
    public fun hasSolarEventAndStatusZGEN(): kotlin.Boolean {
      return _builder.hasSolarEventAndStatusZGEN()
    }

    /**
     * <pre>
     * MISSING DOCUMENTATION!!!
     * </pre>
     *
     * <code>.commonmodule.ENG_GridConnectModeKind GriMod = 2;</code>
     */
    public var griMod: openfmb.commonmodule.ENG_GridConnectModeKind
      @JvmName("getGriMod")
      get() = _builder.getGriMod()
      @JvmName("setGriMod")
      set(value) {
        _builder.setGriMod(value)
      }
    /**
     * <pre>
     * MISSING DOCUMENTATION!!!
     * </pre>
     *
     * <code>.commonmodule.ENG_GridConnectModeKind GriMod = 2;</code>
     */
    public fun clearGriMod() {
      _builder.clearGriMod()
    }
    /**
     * <pre>
     * MISSING DOCUMENTATION!!!
     * </pre>
     *
     * <code>.commonmodule.ENG_GridConnectModeKind GriMod = 2;</code>
     * @return Whether the griMod field is set.
     */
    public fun hasGriMod(): kotlin.Boolean {
      return _builder.hasGriMod()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun openfmb.solarmodule.SolarEventZGEN.copy(block: openfmb.solarmodule.SolarEventZGENKt.Dsl.() -> kotlin.Unit): openfmb.solarmodule.SolarEventZGEN =
  openfmb.solarmodule.SolarEventZGENKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val openfmb.solarmodule.SolarEventZGENOrBuilder.solarEventAndStatusZGENOrNull: openfmb.solarmodule.SolarEventAndStatusZGEN?
  get() = if (hasSolarEventAndStatusZGEN()) getSolarEventAndStatusZGEN() else null

public val openfmb.solarmodule.SolarEventZGENOrBuilder.griModOrNull: openfmb.commonmodule.ENG_GridConnectModeKind?
  get() = if (hasGriMod()) getGriMod() else null

