// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: reclosermodule/reclosermodule.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package openfmb.reclosermodule;

@kotlin.jvm.JvmName("-initializerecloserStatus")
public inline fun recloserStatus(block: openfmb.reclosermodule.RecloserStatusKt.Dsl.() -> kotlin.Unit): openfmb.reclosermodule.RecloserStatus =
  openfmb.reclosermodule.RecloserStatusKt.Dsl._create(openfmb.reclosermodule.RecloserStatus.newBuilder()).apply { block() }._build()
/**
 * ```
 * Recloser status
 * ```
 *
 * Protobuf type `reclosermodule.RecloserStatus`
 */
public object RecloserStatusKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: openfmb.reclosermodule.RecloserStatus.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: openfmb.reclosermodule.RecloserStatus.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): openfmb.reclosermodule.RecloserStatus = _builder.build()

    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.StatusValue statusValue = 1 [(.uml.option_parent_message) = true];`
     */
    public var statusValue: openfmb.commonmodule.StatusValue
      @JvmName("getStatusValue")
      get() = _builder.getStatusValue()
      @JvmName("setStatusValue")
      set(value) {
        _builder.setStatusValue(value)
      }
    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.StatusValue statusValue = 1 [(.uml.option_parent_message) = true];`
     */
    public fun clearStatusValue() {
      _builder.clearStatusValue()
    }
    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.StatusValue statusValue = 1 [(.uml.option_parent_message) = true];`
     * @return Whether the statusValue field is set.
     */
    public fun hasStatusValue(): kotlin.Boolean {
      return _builder.hasStatusValue()
    }

    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.StatusAndEventXCBR statusAndEventXCBR = 2;`
     */
    public var statusAndEventXCBR: openfmb.commonmodule.StatusAndEventXCBR
      @JvmName("getStatusAndEventXCBR")
      get() = _builder.getStatusAndEventXCBR()
      @JvmName("setStatusAndEventXCBR")
      set(value) {
        _builder.setStatusAndEventXCBR(value)
      }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.StatusAndEventXCBR statusAndEventXCBR = 2;`
     */
    public fun clearStatusAndEventXCBR() {
      _builder.clearStatusAndEventXCBR()
    }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.StatusAndEventXCBR statusAndEventXCBR = 2;`
     * @return Whether the statusAndEventXCBR field is set.
     */
    public fun hasStatusAndEventXCBR(): kotlin.Boolean {
      return _builder.hasStatusAndEventXCBR()
    }
  }
}
@kotlin.jvm.JvmSynthetic
@com.google.errorprone.annotations.CheckReturnValue
public inline fun openfmb.reclosermodule.RecloserStatus.copy(block: openfmb.reclosermodule.RecloserStatusKt.Dsl.() -> kotlin.Unit): openfmb.reclosermodule.RecloserStatus =
  openfmb.reclosermodule.RecloserStatusKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val openfmb.reclosermodule.RecloserStatusOrBuilder.statusValueOrNull: openfmb.commonmodule.StatusValue?
  get() = if (hasStatusValue()) getStatusValue() else null

public val openfmb.reclosermodule.RecloserStatusOrBuilder.statusAndEventXCBROrNull: openfmb.commonmodule.StatusAndEventXCBR?
  get() = if (hasStatusAndEventXCBR()) getStatusAndEventXCBR() else null

