// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: reclosermodule/reclosermodule.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package openfmb.reclosermodule;

@kotlin.jvm.JvmName("-initializerecloserDiscreteControlXCBR")
public inline fun recloserDiscreteControlXCBR(block: openfmb.reclosermodule.RecloserDiscreteControlXCBRKt.Dsl.() -> kotlin.Unit): openfmb.reclosermodule.RecloserDiscreteControlXCBR =
  openfmb.reclosermodule.RecloserDiscreteControlXCBRKt.Dsl._create(openfmb.reclosermodule.RecloserDiscreteControlXCBR.newBuilder()).apply { block() }._build()
/**
 * ```
 * Protection mode such as a group setting or pre-defined curve profile. It is usually pre-defined
 * by a circuit segment service.
 * ```
 *
 * Protobuf type `reclosermodule.RecloserDiscreteControlXCBR`
 */
public object RecloserDiscreteControlXCBRKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: openfmb.reclosermodule.RecloserDiscreteControlXCBR.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: openfmb.reclosermodule.RecloserDiscreteControlXCBR.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): openfmb.reclosermodule.RecloserDiscreteControlXCBR = _builder.build()

    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.DiscreteControlXCBR discreteControlXCBR = 1 [(.uml.option_parent_message) = true];`
     */
    public var discreteControlXCBR: openfmb.commonmodule.DiscreteControlXCBR
      @kotlin.jvm.JvmName("getDiscreteControlXCBR")
        get() = _builder.discreteControlXCBR
      @kotlin.jvm.JvmName("setDiscreteControlXCBR")
        set(value) {
        _builder.discreteControlXCBR = value
      }
    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.DiscreteControlXCBR discreteControlXCBR = 1 [(.uml.option_parent_message) = true];`
     */
    public fun clearDiscreteControlXCBR() {
      _builder.clearDiscreteControlXCBR()
    }
    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.DiscreteControlXCBR discreteControlXCBR = 1 [(.uml.option_parent_message) = true];`
     * @return Whether the discreteControlXCBR field is set.
     */
    public fun hasDiscreteControlXCBR(): kotlin.Boolean {
      return _builder.hasDiscreteControlXCBR()
    }

    public val RecloserDiscreteControlXCBRKt.Dsl.discreteControlXCBROrNull: openfmb.commonmodule.DiscreteControlXCBR?
      get() = _builder.discreteControlXCBROrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun openfmb.reclosermodule.RecloserDiscreteControlXCBR.copy(block: `openfmb.reclosermodule`.RecloserDiscreteControlXCBRKt.Dsl.() -> kotlin.Unit): openfmb.reclosermodule.RecloserDiscreteControlXCBR =
  `openfmb.reclosermodule`.RecloserDiscreteControlXCBRKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val openfmb.reclosermodule.RecloserDiscreteControlXCBROrBuilder.discreteControlXCBROrNull: openfmb.commonmodule.DiscreteControlXCBR?
  get() = if (hasDiscreteControlXCBR()) getDiscreteControlXCBR() else null

