// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: essmodule/essmodule.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package openfmb.essmodule;

@kotlin.jvm.JvmName("-initializeessControlFSCC")
public inline fun essControlFSCC(block: openfmb.essmodule.EssControlFSCCKt.Dsl.() -> kotlin.Unit): openfmb.essmodule.EssControlFSCC =
  openfmb.essmodule.EssControlFSCCKt.Dsl._create(openfmb.essmodule.EssControlFSCC.newBuilder()).apply { block() }._build()
/**
 * ```
 * Specialized 61850 FSCC class.  LN: Schedule controller   Name: FSCC
 * ```
 *
 * Protobuf type `essmodule.EssControlFSCC`
 */
public object EssControlFSCCKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: openfmb.essmodule.EssControlFSCC.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: openfmb.essmodule.EssControlFSCC.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): openfmb.essmodule.EssControlFSCC = _builder.build()

    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.ControlFSCC controlFSCC = 1 [(.uml.option_parent_message) = true];`
     */
    public var controlFSCC: openfmb.commonmodule.ControlFSCC
      @JvmName("getControlFSCC")
      get() = _builder.getControlFSCC()
      @JvmName("setControlFSCC")
      set(value) {
        _builder.setControlFSCC(value)
      }
    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.ControlFSCC controlFSCC = 1 [(.uml.option_parent_message) = true];`
     */
    public fun clearControlFSCC() {
      _builder.clearControlFSCC()
    }
    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.ControlFSCC controlFSCC = 1 [(.uml.option_parent_message) = true];`
     * @return Whether the controlFSCC field is set.
     */
    public fun hasControlFSCC(): kotlin.Boolean {
      return _builder.hasControlFSCC()
    }

    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.essmodule.ESSControlScheduleFSCH essControlScheduleFSCH = 2;`
     */
    public var essControlScheduleFSCH: openfmb.essmodule.ESSControlScheduleFSCH
      @JvmName("getEssControlScheduleFSCH")
      get() = _builder.getEssControlScheduleFSCH()
      @JvmName("setEssControlScheduleFSCH")
      set(value) {
        _builder.setEssControlScheduleFSCH(value)
      }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.essmodule.ESSControlScheduleFSCH essControlScheduleFSCH = 2;`
     */
    public fun clearEssControlScheduleFSCH() {
      _builder.clearEssControlScheduleFSCH()
    }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.essmodule.ESSControlScheduleFSCH essControlScheduleFSCH = 2;`
     * @return Whether the essControlScheduleFSCH field is set.
     */
    public fun hasEssControlScheduleFSCH(): kotlin.Boolean {
      return _builder.hasEssControlScheduleFSCH()
    }
  }
}
@kotlin.jvm.JvmSynthetic
@com.google.errorprone.annotations.CheckReturnValue
public inline fun openfmb.essmodule.EssControlFSCC.copy(block: openfmb.essmodule.EssControlFSCCKt.Dsl.() -> kotlin.Unit): openfmb.essmodule.EssControlFSCC =
  openfmb.essmodule.EssControlFSCCKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val openfmb.essmodule.EssControlFSCCOrBuilder.controlFSCCOrNull: openfmb.commonmodule.ControlFSCC?
  get() = if (hasControlFSCC()) getControlFSCC() else null

public val openfmb.essmodule.EssControlFSCCOrBuilder.essControlScheduleFSCHOrNull: openfmb.essmodule.ESSControlScheduleFSCH?
  get() = if (hasEssControlScheduleFSCH()) getEssControlScheduleFSCH() else null

