// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: essmodule/essmodule.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package openfmb.essmodule;

@kotlin.jvm.JvmName("-initializeeSSControlScheduleFSCH")
public inline fun eSSControlScheduleFSCH(block: openfmb.essmodule.ESSControlScheduleFSCHKt.Dsl.() -> kotlin.Unit): openfmb.essmodule.ESSControlScheduleFSCH =
  openfmb.essmodule.ESSControlScheduleFSCHKt.Dsl._create(openfmb.essmodule.ESSControlScheduleFSCH.newBuilder()).apply { block() }._build()
/**
 * ```
 * OpenFMB specialization for control schedule using:  LN: Schedule   Name: FSCH
 * ```
 *
 * Protobuf type `essmodule.ESSControlScheduleFSCH`
 */
public object ESSControlScheduleFSCHKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: openfmb.essmodule.ESSControlScheduleFSCH.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: openfmb.essmodule.ESSControlScheduleFSCH.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): openfmb.essmodule.ESSControlScheduleFSCH = _builder.build()

    /**
     * ```
     * Discrete value in ESSCSG type
     * ```
     *
     * `.essmodule.ESSCSG ValDCSG = 1 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];`
     */
    public var valDCSG: openfmb.essmodule.ESSCSG
      @JvmName("getValDCSG")
      get() = _builder.getValDCSG()
      @JvmName("setValDCSG")
      set(value) {
        _builder.setValDCSG(value)
      }
    /**
     * ```
     * Discrete value in ESSCSG type
     * ```
     *
     * `.essmodule.ESSCSG ValDCSG = 1 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];`
     */
    public fun clearValDCSG() {
      _builder.clearValDCSG()
    }
    /**
     * ```
     * Discrete value in ESSCSG type
     * ```
     *
     * `.essmodule.ESSCSG ValDCSG = 1 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];`
     * @return Whether the valDCSG field is set.
     */
    public fun hasValDCSG(): kotlin.Boolean {
      return _builder.hasValDCSG()
    }
  }
}
@kotlin.jvm.JvmSynthetic
@com.google.errorprone.annotations.CheckReturnValue
public inline fun openfmb.essmodule.ESSControlScheduleFSCH.copy(block: openfmb.essmodule.ESSControlScheduleFSCHKt.Dsl.() -> kotlin.Unit): openfmb.essmodule.ESSControlScheduleFSCH =
  openfmb.essmodule.ESSControlScheduleFSCHKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val openfmb.essmodule.ESSControlScheduleFSCHOrBuilder.valDCSGOrNull: openfmb.essmodule.ESSCSG?
  get() = if (hasValDCSG()) getValDCSG() else null

