// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: essmodule/essmodule.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package openfmb.essmodule;

@kotlin.jvm.JvmName("-initializeessStatusZBAT")
public inline fun essStatusZBAT(block: openfmb.essmodule.EssStatusZBATKt.Dsl.() -> kotlin.Unit): openfmb.essmodule.EssStatusZBAT =
  openfmb.essmodule.EssStatusZBATKt.Dsl._create(openfmb.essmodule.EssStatusZBAT.newBuilder()).apply { block() }._build()
/**
 * ```
 * Specialized 61850 ZBAT
 * ```
 *
 * Protobuf type `essmodule.EssStatusZBAT`
 */
public object EssStatusZBATKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: openfmb.essmodule.EssStatusZBAT.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: openfmb.essmodule.EssStatusZBAT.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): openfmb.essmodule.EssStatusZBAT = _builder.build()

    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.LogicalNodeForEventAndStatus logicalNodeForEventAndStatus = 1 [(.uml.option_parent_message) = true];`
     */
    public var logicalNodeForEventAndStatus: openfmb.commonmodule.LogicalNodeForEventAndStatus
      @kotlin.jvm.JvmName("getLogicalNodeForEventAndStatus")
        get() = _builder.logicalNodeForEventAndStatus
      @kotlin.jvm.JvmName("setLogicalNodeForEventAndStatus")
        set(value) {
        _builder.logicalNodeForEventAndStatus = value
      }
    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.LogicalNodeForEventAndStatus logicalNodeForEventAndStatus = 1 [(.uml.option_parent_message) = true];`
     */
    public fun clearLogicalNodeForEventAndStatus() {
      _builder.clearLogicalNodeForEventAndStatus()
    }
    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.LogicalNodeForEventAndStatus logicalNodeForEventAndStatus = 1 [(.uml.option_parent_message) = true];`
     * @return Whether the logicalNodeForEventAndStatus field is set.
     */
    public fun hasLogicalNodeForEventAndStatus(): kotlin.Boolean {
      return _builder.hasLogicalNodeForEventAndStatus()
    }

    public val EssStatusZBATKt.Dsl.logicalNodeForEventAndStatusOrNull: openfmb.commonmodule.LogicalNodeForEventAndStatus?
      get() = _builder.logicalNodeForEventAndStatusOrNull

    /**
     * ```
     * Battery system status &ndash; True: on
     * ```
     *
     * `.commonmodule.StatusSPS BatSt = 2;`
     */
    public var batSt: openfmb.commonmodule.StatusSPS
      @kotlin.jvm.JvmName("getBatSt")
        get() = _builder.batSt
      @kotlin.jvm.JvmName("setBatSt")
        set(value) {
        _builder.batSt = value
      }
    /**
     * ```
     * Battery system status &ndash; True: on
     * ```
     *
     * `.commonmodule.StatusSPS BatSt = 2;`
     */
    public fun clearBatSt() {
      _builder.clearBatSt()
    }
    /**
     * ```
     * Battery system status &ndash; True: on
     * ```
     *
     * `.commonmodule.StatusSPS BatSt = 2;`
     * @return Whether the batSt field is set.
     */
    public fun hasBatSt(): kotlin.Boolean {
      return _builder.hasBatSt()
    }

    public val EssStatusZBATKt.Dsl.batStOrNull: openfmb.commonmodule.StatusSPS?
      get() = _builder.batStOrNull

    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.ENG_GridConnectModeKind GriMod = 3;`
     */
    public var griMod: openfmb.commonmodule.ENG_GridConnectModeKind
      @kotlin.jvm.JvmName("getGriMod")
        get() = _builder.griMod
      @kotlin.jvm.JvmName("setGriMod")
        set(value) {
        _builder.griMod = value
      }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.ENG_GridConnectModeKind GriMod = 3;`
     */
    public fun clearGriMod() {
      _builder.clearGriMod()
    }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.ENG_GridConnectModeKind GriMod = 3;`
     * @return Whether the griMod field is set.
     */
    public fun hasGriMod(): kotlin.Boolean {
      return _builder.hasGriMod()
    }

    public val EssStatusZBATKt.Dsl.griModOrNull: openfmb.commonmodule.ENG_GridConnectModeKind?
      get() = _builder.griModOrNull

    /**
     * ```
     * State of charge (in percentage)
     * ```
     *
     * `.commonmodule.MV Soc = 4;`
     */
    public var soc: openfmb.commonmodule.MV
      @kotlin.jvm.JvmName("getSoc")
        get() = _builder.soc
      @kotlin.jvm.JvmName("setSoc")
        set(value) {
        _builder.soc = value
      }
    /**
     * ```
     * State of charge (in percentage)
     * ```
     *
     * `.commonmodule.MV Soc = 4;`
     */
    public fun clearSoc() {
      _builder.clearSoc()
    }
    /**
     * ```
     * State of charge (in percentage)
     * ```
     *
     * `.commonmodule.MV Soc = 4;`
     * @return Whether the soc field is set.
     */
    public fun hasSoc(): kotlin.Boolean {
      return _builder.hasSoc()
    }

    public val EssStatusZBATKt.Dsl.socOrNull: openfmb.commonmodule.MV?
      get() = _builder.socOrNull

    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.StatusSPS Stdby = 5;`
     */
    public var stdby: openfmb.commonmodule.StatusSPS
      @kotlin.jvm.JvmName("getStdby")
        get() = _builder.stdby
      @kotlin.jvm.JvmName("setStdby")
        set(value) {
        _builder.stdby = value
      }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.StatusSPS Stdby = 5;`
     */
    public fun clearStdby() {
      _builder.clearStdby()
    }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.StatusSPS Stdby = 5;`
     * @return Whether the stdby field is set.
     */
    public fun hasStdby(): kotlin.Boolean {
      return _builder.hasStdby()
    }

    public val EssStatusZBATKt.Dsl.stdbyOrNull: openfmb.commonmodule.StatusSPS?
      get() = _builder.stdbyOrNull

    /**
     * ```
     * State of health of the DER storage.
     * ```
     *
     * `.commonmodule.MV SoH = 6;`
     */
    public var soH: openfmb.commonmodule.MV
      @kotlin.jvm.JvmName("getSoH")
        get() = _builder.soH
      @kotlin.jvm.JvmName("setSoH")
        set(value) {
        _builder.soH = value
      }
    /**
     * ```
     * State of health of the DER storage.
     * ```
     *
     * `.commonmodule.MV SoH = 6;`
     */
    public fun clearSoH() {
      _builder.clearSoH()
    }
    /**
     * ```
     * State of health of the DER storage.
     * ```
     *
     * `.commonmodule.MV SoH = 6;`
     * @return Whether the soH field is set.
     */
    public fun hasSoH(): kotlin.Boolean {
      return _builder.hasSoH()
    }

    public val EssStatusZBATKt.Dsl.soHOrNull: openfmb.commonmodule.MV?
      get() = _builder.soHOrNull

    /**
     * ```
     * Energy available of the DER storage (WHAvail = WHRtg * SoC * SoH)
     * ```
     *
     * `.commonmodule.MV WHAvail = 7;`
     */
    public var wHAvail: openfmb.commonmodule.MV
      @kotlin.jvm.JvmName("getWHAvail")
        get() = _builder.whAvail
      @kotlin.jvm.JvmName("setWHAvail")
        set(value) {
        _builder.whAvail = value
      }
    /**
     * ```
     * Energy available of the DER storage (WHAvail = WHRtg * SoC * SoH)
     * ```
     *
     * `.commonmodule.MV WHAvail = 7;`
     */
    public fun clearWHAvail() {
      _builder.clearWHAvail()
    }
    /**
     * ```
     * Energy available of the DER storage (WHAvail = WHRtg * SoC * SoH)
     * ```
     *
     * `.commonmodule.MV WHAvail = 7;`
     * @return Whether the wHAvail field is set.
     */
    public fun hasWHAvail(): kotlin.Boolean {
      return _builder.hasWHAvail()
    }

    public val EssStatusZBATKt.Dsl.wHAvailOrNull: openfmb.commonmodule.MV?
      get() = _builder.wHAvailOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun openfmb.essmodule.EssStatusZBAT.copy(block: `openfmb.essmodule`.EssStatusZBATKt.Dsl.() -> kotlin.Unit): openfmb.essmodule.EssStatusZBAT =
  `openfmb.essmodule`.EssStatusZBATKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val openfmb.essmodule.EssStatusZBATOrBuilder.logicalNodeForEventAndStatusOrNull: openfmb.commonmodule.LogicalNodeForEventAndStatus?
  get() = if (hasLogicalNodeForEventAndStatus()) getLogicalNodeForEventAndStatus() else null

public val openfmb.essmodule.EssStatusZBATOrBuilder.batStOrNull: openfmb.commonmodule.StatusSPS?
  get() = if (hasBatSt()) getBatSt() else null

public val openfmb.essmodule.EssStatusZBATOrBuilder.griModOrNull: openfmb.commonmodule.ENG_GridConnectModeKind?
  get() = if (hasGriMod()) getGriMod() else null

public val openfmb.essmodule.EssStatusZBATOrBuilder.socOrNull: openfmb.commonmodule.MV?
  get() = if (hasSoc()) getSoc() else null

public val openfmb.essmodule.EssStatusZBATOrBuilder.stdbyOrNull: openfmb.commonmodule.StatusSPS?
  get() = if (hasStdby()) getStdby() else null

public val openfmb.essmodule.EssStatusZBATOrBuilder.soHOrNull: openfmb.commonmodule.MV?
  get() = if (hasSoH()) getSoH() else null

public val openfmb.essmodule.EssStatusZBATOrBuilder.wHAvailOrNull: openfmb.commonmodule.MV?
  get() = if (hasWHAvail()) getWHAvail() else null

