// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: metermodule/metermodule.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package openfmb.metermodule;

@kotlin.jvm.JvmName("-initializemeterReadingProfile")
public inline fun meterReadingProfile(block: openfmb.metermodule.MeterReadingProfileKt.Dsl.() -> kotlin.Unit): openfmb.metermodule.MeterReadingProfile =
  openfmb.metermodule.MeterReadingProfileKt.Dsl._create(openfmb.metermodule.MeterReadingProfile.newBuilder()).apply { block() }._build()
/**
 * ```
 * Resource reading profile
 * ```
 *
 * Protobuf type `metermodule.MeterReadingProfile`
 */
public object MeterReadingProfileKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: openfmb.metermodule.MeterReadingProfile.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: openfmb.metermodule.MeterReadingProfile.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): openfmb.metermodule.MeterReadingProfile = _builder.build()

    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.ReadingMessageInfo readingMessageInfo = 1 [(.uml.option_parent_message) = true];`
     */
    public var readingMessageInfo: openfmb.commonmodule.ReadingMessageInfo
      @JvmName("getReadingMessageInfo")
      get() = _builder.getReadingMessageInfo()
      @JvmName("setReadingMessageInfo")
      set(value) {
        _builder.setReadingMessageInfo(value)
      }
    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.ReadingMessageInfo readingMessageInfo = 1 [(.uml.option_parent_message) = true];`
     */
    public fun clearReadingMessageInfo() {
      _builder.clearReadingMessageInfo()
    }
    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.ReadingMessageInfo readingMessageInfo = 1 [(.uml.option_parent_message) = true];`
     * @return Whether the readingMessageInfo field is set.
     */
    public fun hasReadingMessageInfo(): kotlin.Boolean {
      return _builder.hasReadingMessageInfo()
    }

    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.Meter meter = 2 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];`
     */
    public var meter: openfmb.commonmodule.Meter
      @JvmName("getMeter")
      get() = _builder.getMeter()
      @JvmName("setMeter")
      set(value) {
        _builder.setMeter(value)
      }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.Meter meter = 2 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];`
     */
    public fun clearMeter() {
      _builder.clearMeter()
    }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.Meter meter = 2 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];`
     * @return Whether the meter field is set.
     */
    public fun hasMeter(): kotlin.Boolean {
      return _builder.hasMeter()
    }

    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.metermodule.MeterReading meterReading = 3 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];`
     */
    public var meterReading: openfmb.metermodule.MeterReading
      @JvmName("getMeterReading")
      get() = _builder.getMeterReading()
      @JvmName("setMeterReading")
      set(value) {
        _builder.setMeterReading(value)
      }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.metermodule.MeterReading meterReading = 3 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];`
     */
    public fun clearMeterReading() {
      _builder.clearMeterReading()
    }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.metermodule.MeterReading meterReading = 3 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];`
     * @return Whether the meterReading field is set.
     */
    public fun hasMeterReading(): kotlin.Boolean {
      return _builder.hasMeterReading()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun openfmb.metermodule.MeterReadingProfile.copy(block: openfmb.metermodule.MeterReadingProfileKt.Dsl.() -> kotlin.Unit): openfmb.metermodule.MeterReadingProfile =
  openfmb.metermodule.MeterReadingProfileKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val openfmb.metermodule.MeterReadingProfileOrBuilder.readingMessageInfoOrNull: openfmb.commonmodule.ReadingMessageInfo?
  get() = if (hasReadingMessageInfo()) getReadingMessageInfo() else null

public val openfmb.metermodule.MeterReadingProfileOrBuilder.meterOrNull: openfmb.commonmodule.Meter?
  get() = if (hasMeter()) getMeter() else null

public val openfmb.metermodule.MeterReadingProfileOrBuilder.meterReadingOrNull: openfmb.metermodule.MeterReading?
  get() = if (hasMeterReading()) getMeterReading() else null

