//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: generationmodule/generationmodule.proto

package openfmb.generationmodule;

@kotlin.jvm.JvmName("-initializegenerationControlScheduleFSCH")
public inline fun generationControlScheduleFSCH(block: openfmb.generationmodule.GenerationControlScheduleFSCHKt.Dsl.() -> kotlin.Unit): openfmb.generationmodule.GenerationControlScheduleFSCH =
  openfmb.generationmodule.GenerationControlScheduleFSCHKt.Dsl._create(openfmb.generationmodule.GenerationControlScheduleFSCH.newBuilder()).apply { block() }._build()
public object GenerationControlScheduleFSCHKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: openfmb.generationmodule.GenerationControlScheduleFSCH.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: openfmb.generationmodule.GenerationControlScheduleFSCH.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): openfmb.generationmodule.GenerationControlScheduleFSCH = _builder.build()

    /**
     * <pre>
     * Discrete value in GenerationCSG type
     * </pre>
     *
     * <code>.generationmodule.GenerationCSG ValDCSG = 1 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public var valDCSG: openfmb.generationmodule.GenerationCSG
      @JvmName("getValDCSG")
      get() = _builder.getValDCSG()
      @JvmName("setValDCSG")
      set(value) {
        _builder.setValDCSG(value)
      }
    /**
     * <pre>
     * Discrete value in GenerationCSG type
     * </pre>
     *
     * <code>.generationmodule.GenerationCSG ValDCSG = 1 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public fun clearValDCSG() {
      _builder.clearValDCSG()
    }
    /**
     * <pre>
     * Discrete value in GenerationCSG type
     * </pre>
     *
     * <code>.generationmodule.GenerationCSG ValDCSG = 1 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     * @return Whether the valDCSG field is set.
     */
    public fun hasValDCSG(): kotlin.Boolean {
      return _builder.hasValDCSG()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun openfmb.generationmodule.GenerationControlScheduleFSCH.copy(block: openfmb.generationmodule.GenerationControlScheduleFSCHKt.Dsl.() -> kotlin.Unit): openfmb.generationmodule.GenerationControlScheduleFSCH =
  openfmb.generationmodule.GenerationControlScheduleFSCHKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val openfmb.generationmodule.GenerationControlScheduleFSCHOrBuilder.valDCSGOrNull: openfmb.generationmodule.GenerationCSG?
  get() = if (hasValDCSG()) getValDCSG() else null

