// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: generationmodule/generationmodule.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package openfmb.generationmodule;

@kotlin.jvm.JvmName("-initializegenerationDiscreteControl")
public inline fun generationDiscreteControl(block: openfmb.generationmodule.GenerationDiscreteControlKt.Dsl.() -> kotlin.Unit): openfmb.generationmodule.GenerationDiscreteControl =
  openfmb.generationmodule.GenerationDiscreteControlKt.Dsl._create(openfmb.generationmodule.GenerationDiscreteControl.newBuilder()).apply { block() }._build()
/**
 * ```
 * Generation discrete control
 * ```
 *
 * Protobuf type `generationmodule.GenerationDiscreteControl`
 */
public object GenerationDiscreteControlKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: openfmb.generationmodule.GenerationDiscreteControl.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: openfmb.generationmodule.GenerationDiscreteControl.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): openfmb.generationmodule.GenerationDiscreteControl = _builder.build()

    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.ControlValue controlValue = 1 [(.uml.option_parent_message) = true];`
     */
    public var controlValue: openfmb.commonmodule.ControlValue
      @JvmName("getControlValue")
      get() = _builder.getControlValue()
      @JvmName("setControlValue")
      set(value) {
        _builder.setControlValue(value)
      }
    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.ControlValue controlValue = 1 [(.uml.option_parent_message) = true];`
     */
    public fun clearControlValue() {
      _builder.clearControlValue()
    }
    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.ControlValue controlValue = 1 [(.uml.option_parent_message) = true];`
     * @return Whether the controlValue field is set.
     */
    public fun hasControlValue(): kotlin.Boolean {
      return _builder.hasControlValue()
    }

    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.CheckConditions check = 2;`
     */
    public var check: openfmb.commonmodule.CheckConditions
      @JvmName("getCheck")
      get() = _builder.getCheck()
      @JvmName("setCheck")
      set(value) {
        _builder.setCheck(value)
      }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.CheckConditions check = 2;`
     */
    public fun clearCheck() {
      _builder.clearCheck()
    }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.CheckConditions check = 2;`
     * @return Whether the check field is set.
     */
    public fun hasCheck(): kotlin.Boolean {
      return _builder.hasCheck()
    }

    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.generationmodule.ReactivePowerControl ReactivePowerControl = 3;`
     */
    public var reactivePowerControl: openfmb.generationmodule.ReactivePowerControl
      @JvmName("getReactivePowerControl")
      get() = _builder.getReactivePowerControl()
      @JvmName("setReactivePowerControl")
      set(value) {
        _builder.setReactivePowerControl(value)
      }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.generationmodule.ReactivePowerControl ReactivePowerControl = 3;`
     */
    public fun clearReactivePowerControl() {
      _builder.clearReactivePowerControl()
    }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.generationmodule.ReactivePowerControl ReactivePowerControl = 3;`
     * @return Whether the reactivePowerControl field is set.
     */
    public fun hasReactivePowerControl(): kotlin.Boolean {
      return _builder.hasReactivePowerControl()
    }

    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.generationmodule.RealPowerControl RealPowerControl = 4;`
     */
    public var realPowerControl: openfmb.generationmodule.RealPowerControl
      @JvmName("getRealPowerControl")
      get() = _builder.getRealPowerControl()
      @JvmName("setRealPowerControl")
      set(value) {
        _builder.setRealPowerControl(value)
      }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.generationmodule.RealPowerControl RealPowerControl = 4;`
     */
    public fun clearRealPowerControl() {
      _builder.clearRealPowerControl()
    }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.generationmodule.RealPowerControl RealPowerControl = 4;`
     * @return Whether the realPowerControl field is set.
     */
    public fun hasRealPowerControl(): kotlin.Boolean {
      return _builder.hasRealPowerControl()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun openfmb.generationmodule.GenerationDiscreteControl.copy(block: openfmb.generationmodule.GenerationDiscreteControlKt.Dsl.() -> kotlin.Unit): openfmb.generationmodule.GenerationDiscreteControl =
  openfmb.generationmodule.GenerationDiscreteControlKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val openfmb.generationmodule.GenerationDiscreteControlOrBuilder.controlValueOrNull: openfmb.commonmodule.ControlValue?
  get() = if (hasControlValue()) getControlValue() else null

public val openfmb.generationmodule.GenerationDiscreteControlOrBuilder.checkOrNull: openfmb.commonmodule.CheckConditions?
  get() = if (hasCheck()) getCheck() else null

public val openfmb.generationmodule.GenerationDiscreteControlOrBuilder.reactivePowerControlOrNull: openfmb.generationmodule.ReactivePowerControl?
  get() = if (hasReactivePowerControl()) getReactivePowerControl() else null

public val openfmb.generationmodule.GenerationDiscreteControlOrBuilder.realPowerControlOrNull: openfmb.generationmodule.RealPowerControl?
  get() = if (hasRealPowerControl()) getRealPowerControl() else null

