// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: generationmodule/generationmodule.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package openfmb.generationmodule;

@kotlin.jvm.JvmName("-initializegenerationEventAndStatusZGEN")
public inline fun generationEventAndStatusZGEN(block: openfmb.generationmodule.GenerationEventAndStatusZGENKt.Dsl.() -> kotlin.Unit): openfmb.generationmodule.GenerationEventAndStatusZGEN =
  openfmb.generationmodule.GenerationEventAndStatusZGENKt.Dsl._create(openfmb.generationmodule.GenerationEventAndStatusZGEN.newBuilder()).apply { block() }._build()
/**
 * ```
 * Specialized 61850 ZGEN class
 * ```
 *
 * Protobuf type `generationmodule.GenerationEventAndStatusZGEN`
 */
public object GenerationEventAndStatusZGENKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: openfmb.generationmodule.GenerationEventAndStatusZGEN.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: openfmb.generationmodule.GenerationEventAndStatusZGEN.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): openfmb.generationmodule.GenerationEventAndStatusZGEN = _builder.build()

    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.LogicalNodeForEventAndStatus logicalNodeForEventAndStatus = 1 [(.uml.option_parent_message) = true];`
     */
    public var logicalNodeForEventAndStatus: openfmb.commonmodule.LogicalNodeForEventAndStatus
      @JvmName("getLogicalNodeForEventAndStatus")
      get() = _builder.getLogicalNodeForEventAndStatus()
      @JvmName("setLogicalNodeForEventAndStatus")
      set(value) {
        _builder.setLogicalNodeForEventAndStatus(value)
      }
    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.LogicalNodeForEventAndStatus logicalNodeForEventAndStatus = 1 [(.uml.option_parent_message) = true];`
     */
    public fun clearLogicalNodeForEventAndStatus() {
      _builder.clearLogicalNodeForEventAndStatus()
    }
    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.LogicalNodeForEventAndStatus logicalNodeForEventAndStatus = 1 [(.uml.option_parent_message) = true];`
     * @return Whether the logicalNodeForEventAndStatus field is set.
     */
    public fun hasLogicalNodeForEventAndStatus(): kotlin.Boolean {
      return _builder.hasLogicalNodeForEventAndStatus()
    }

    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.StatusSPS AuxPwrSt = 2;`
     */
    public var auxPwrSt: openfmb.commonmodule.StatusSPS
      @JvmName("getAuxPwrSt")
      get() = _builder.getAuxPwrSt()
      @JvmName("setAuxPwrSt")
      set(value) {
        _builder.setAuxPwrSt(value)
      }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.StatusSPS AuxPwrSt = 2;`
     */
    public fun clearAuxPwrSt() {
      _builder.clearAuxPwrSt()
    }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.StatusSPS AuxPwrSt = 2;`
     * @return Whether the auxPwrSt field is set.
     */
    public fun hasAuxPwrSt(): kotlin.Boolean {
      return _builder.hasAuxPwrSt()
    }

    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.ENS_DynamicTestKind DynamicTest = 3;`
     */
    public var dynamicTest: openfmb.commonmodule.ENS_DynamicTestKind
      @JvmName("getDynamicTest")
      get() = _builder.getDynamicTest()
      @JvmName("setDynamicTest")
      set(value) {
        _builder.setDynamicTest(value)
      }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.ENS_DynamicTestKind DynamicTest = 3;`
     */
    public fun clearDynamicTest() {
      _builder.clearDynamicTest()
    }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.ENS_DynamicTestKind DynamicTest = 3;`
     * @return Whether the dynamicTest field is set.
     */
    public fun hasDynamicTest(): kotlin.Boolean {
      return _builder.hasDynamicTest()
    }

    /**
     * ```
     * Emergency stop
     * ```
     *
     * `.commonmodule.StatusSPS EmgStop = 4;`
     */
    public var emgStop: openfmb.commonmodule.StatusSPS
      @JvmName("getEmgStop")
      get() = _builder.getEmgStop()
      @JvmName("setEmgStop")
      set(value) {
        _builder.setEmgStop(value)
      }
    /**
     * ```
     * Emergency stop
     * ```
     *
     * `.commonmodule.StatusSPS EmgStop = 4;`
     */
    public fun clearEmgStop() {
      _builder.clearEmgStop()
    }
    /**
     * ```
     * Emergency stop
     * ```
     *
     * `.commonmodule.StatusSPS EmgStop = 4;`
     * @return Whether the emgStop field is set.
     */
    public fun hasEmgStop(): kotlin.Boolean {
      return _builder.hasEmgStop()
    }

    /**
     * ```
     * Generator is synchronized to EPS, or not; True = Synchronized
     * ```
     *
     * `.commonmodule.StatusSPS GnSynSt = 5;`
     */
    public var gnSynSt: openfmb.commonmodule.StatusSPS
      @JvmName("getGnSynSt")
      get() = _builder.getGnSynSt()
      @JvmName("setGnSynSt")
      set(value) {
        _builder.setGnSynSt(value)
      }
    /**
     * ```
     * Generator is synchronized to EPS, or not; True = Synchronized
     * ```
     *
     * `.commonmodule.StatusSPS GnSynSt = 5;`
     */
    public fun clearGnSynSt() {
      _builder.clearGnSynSt()
    }
    /**
     * ```
     * Generator is synchronized to EPS, or not; True = Synchronized
     * ```
     *
     * `.commonmodule.StatusSPS GnSynSt = 5;`
     * @return Whether the gnSynSt field is set.
     */
    public fun hasGnSynSt(): kotlin.Boolean {
      return _builder.hasGnSynSt()
    }

    /**
     * ```
     * Point status
     * ```
     *
     * `.generationmodule.GenerationPointStatus PointStatus = 6;`
     */
    public var pointStatus: openfmb.generationmodule.GenerationPointStatus
      @JvmName("getPointStatus")
      get() = _builder.getPointStatus()
      @JvmName("setPointStatus")
      set(value) {
        _builder.setPointStatus(value)
      }
    /**
     * ```
     * Point status
     * ```
     *
     * `.generationmodule.GenerationPointStatus PointStatus = 6;`
     */
    public fun clearPointStatus() {
      _builder.clearPointStatus()
    }
    /**
     * ```
     * Point status
     * ```
     *
     * `.generationmodule.GenerationPointStatus PointStatus = 6;`
     * @return Whether the pointStatus field is set.
     */
    public fun hasPointStatus(): kotlin.Boolean {
      return _builder.hasPointStatus()
    }

    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.Optional_AlrmKind Alrm = 7;`
     */
    public var alrm: openfmb.commonmodule.Optional_AlrmKind
      @JvmName("getAlrm")
      get() = _builder.getAlrm()
      @JvmName("setAlrm")
      set(value) {
        _builder.setAlrm(value)
      }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.Optional_AlrmKind Alrm = 7;`
     */
    public fun clearAlrm() {
      _builder.clearAlrm()
    }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.Optional_AlrmKind Alrm = 7;`
     * @return Whether the alrm field is set.
     */
    public fun hasAlrm(): kotlin.Boolean {
      return _builder.hasAlrm()
    }

    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.Optional_GridConnectionStateKind GridConnectionState = 8;`
     */
    public var gridConnectionState: openfmb.commonmodule.Optional_GridConnectionStateKind
      @JvmName("getGridConnectionState")
      get() = _builder.getGridConnectionState()
      @JvmName("setGridConnectionState")
      set(value) {
        _builder.setGridConnectionState(value)
      }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.Optional_GridConnectionStateKind GridConnectionState = 8;`
     */
    public fun clearGridConnectionState() {
      _builder.clearGridConnectionState()
    }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.Optional_GridConnectionStateKind GridConnectionState = 8;`
     * @return Whether the gridConnectionState field is set.
     */
    public fun hasGridConnectionState(): kotlin.Boolean {
      return _builder.hasGridConnectionState()
    }

    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.google.protobuf.StringValue ManAlrmInfo = 9;`
     */
    public var manAlrmInfo: com.google.protobuf.StringValue
      @JvmName("getManAlrmInfo")
      get() = _builder.getManAlrmInfo()
      @JvmName("setManAlrmInfo")
      set(value) {
        _builder.setManAlrmInfo(value)
      }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.google.protobuf.StringValue ManAlrmInfo = 9;`
     */
    public fun clearManAlrmInfo() {
      _builder.clearManAlrmInfo()
    }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.google.protobuf.StringValue ManAlrmInfo = 9;`
     * @return Whether the manAlrmInfo field is set.
     */
    public fun hasManAlrmInfo(): kotlin.Boolean {
      return _builder.hasManAlrmInfo()
    }

    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.Optional_OperatingStateKind OperatingState = 10;`
     */
    public var operatingState: openfmb.commonmodule.Optional_OperatingStateKind
      @JvmName("getOperatingState")
      get() = _builder.getOperatingState()
      @JvmName("setOperatingState")
      set(value) {
        _builder.setOperatingState(value)
      }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.Optional_OperatingStateKind OperatingState = 10;`
     */
    public fun clearOperatingState() {
      _builder.clearOperatingState()
    }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.Optional_OperatingStateKind OperatingState = 10;`
     * @return Whether the operatingState field is set.
     */
    public fun hasOperatingState(): kotlin.Boolean {
      return _builder.hasOperatingState()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun openfmb.generationmodule.GenerationEventAndStatusZGEN.copy(block: openfmb.generationmodule.GenerationEventAndStatusZGENKt.Dsl.() -> kotlin.Unit): openfmb.generationmodule.GenerationEventAndStatusZGEN =
  openfmb.generationmodule.GenerationEventAndStatusZGENKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val openfmb.generationmodule.GenerationEventAndStatusZGENOrBuilder.logicalNodeForEventAndStatusOrNull: openfmb.commonmodule.LogicalNodeForEventAndStatus?
  get() = if (hasLogicalNodeForEventAndStatus()) getLogicalNodeForEventAndStatus() else null

public val openfmb.generationmodule.GenerationEventAndStatusZGENOrBuilder.auxPwrStOrNull: openfmb.commonmodule.StatusSPS?
  get() = if (hasAuxPwrSt()) getAuxPwrSt() else null

public val openfmb.generationmodule.GenerationEventAndStatusZGENOrBuilder.dynamicTestOrNull: openfmb.commonmodule.ENS_DynamicTestKind?
  get() = if (hasDynamicTest()) getDynamicTest() else null

public val openfmb.generationmodule.GenerationEventAndStatusZGENOrBuilder.emgStopOrNull: openfmb.commonmodule.StatusSPS?
  get() = if (hasEmgStop()) getEmgStop() else null

public val openfmb.generationmodule.GenerationEventAndStatusZGENOrBuilder.gnSynStOrNull: openfmb.commonmodule.StatusSPS?
  get() = if (hasGnSynSt()) getGnSynSt() else null

public val openfmb.generationmodule.GenerationEventAndStatusZGENOrBuilder.pointStatusOrNull: openfmb.generationmodule.GenerationPointStatus?
  get() = if (hasPointStatus()) getPointStatus() else null

public val openfmb.generationmodule.GenerationEventAndStatusZGENOrBuilder.alrmOrNull: openfmb.commonmodule.Optional_AlrmKind?
  get() = if (hasAlrm()) getAlrm() else null

public val openfmb.generationmodule.GenerationEventAndStatusZGENOrBuilder.gridConnectionStateOrNull: openfmb.commonmodule.Optional_GridConnectionStateKind?
  get() = if (hasGridConnectionState()) getGridConnectionState() else null

public val openfmb.generationmodule.GenerationEventAndStatusZGENOrBuilder.manAlrmInfoOrNull: com.google.protobuf.StringValue?
  get() = if (hasManAlrmInfo()) getManAlrmInfo() else null

public val openfmb.generationmodule.GenerationEventAndStatusZGENOrBuilder.operatingStateOrNull: openfmb.commonmodule.Optional_OperatingStateKind?
  get() = if (hasOperatingState()) getOperatingState() else null

