//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: interconnectionmodule/interconnectionmodule.proto

package openfmb.interconnectionmodule;

@kotlin.jvm.JvmName("-initializeinterconnectionControlScheduleFSCH")
public inline fun interconnectionControlScheduleFSCH(block: openfmb.interconnectionmodule.InterconnectionControlScheduleFSCHKt.Dsl.() -> kotlin.Unit): openfmb.interconnectionmodule.InterconnectionControlScheduleFSCH =
  openfmb.interconnectionmodule.InterconnectionControlScheduleFSCHKt.Dsl._create(openfmb.interconnectionmodule.InterconnectionControlScheduleFSCH.newBuilder()).apply { block() }._build()
public object InterconnectionControlScheduleFSCHKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: openfmb.interconnectionmodule.InterconnectionControlScheduleFSCH.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: openfmb.interconnectionmodule.InterconnectionControlScheduleFSCH.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): openfmb.interconnectionmodule.InterconnectionControlScheduleFSCH = _builder.build()

    /**
     * <pre>
     * Discrete value in InterconnectionCSG type
     * </pre>
     *
     * <code>.interconnectionmodule.InterconnectionCSG ValDCSG = 1 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public var valDCSG: openfmb.interconnectionmodule.InterconnectionCSG
      @JvmName("getValDCSG")
      get() = _builder.getValDCSG()
      @JvmName("setValDCSG")
      set(value) {
        _builder.setValDCSG(value)
      }
    /**
     * <pre>
     * Discrete value in InterconnectionCSG type
     * </pre>
     *
     * <code>.interconnectionmodule.InterconnectionCSG ValDCSG = 1 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     */
    public fun clearValDCSG() {
      _builder.clearValDCSG()
    }
    /**
     * <pre>
     * Discrete value in InterconnectionCSG type
     * </pre>
     *
     * <code>.interconnectionmodule.InterconnectionCSG ValDCSG = 1 [(.uml.option_required_field) = true, (.uml.option_multiplicity_min) = 1];</code>
     * @return Whether the valDCSG field is set.
     */
    public fun hasValDCSG(): kotlin.Boolean {
      return _builder.hasValDCSG()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun openfmb.interconnectionmodule.InterconnectionControlScheduleFSCH.copy(block: openfmb.interconnectionmodule.InterconnectionControlScheduleFSCHKt.Dsl.() -> kotlin.Unit): openfmb.interconnectionmodule.InterconnectionControlScheduleFSCH =
  openfmb.interconnectionmodule.InterconnectionControlScheduleFSCHKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val openfmb.interconnectionmodule.InterconnectionControlScheduleFSCHOrBuilder.valDCSGOrNull: openfmb.interconnectionmodule.InterconnectionCSG?
  get() = if (hasValDCSG()) getValDCSG() else null

