// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: circuitsegmentservicemodule/circuitsegmentservicemodule.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package openfmb.circuitsegmentservicemodule;

@kotlin.jvm.JvmName("-initializecircuitSegmentControlDCSC")
public inline fun circuitSegmentControlDCSC(block: openfmb.circuitsegmentservicemodule.CircuitSegmentControlDCSCKt.Dsl.() -> kotlin.Unit): openfmb.circuitsegmentservicemodule.CircuitSegmentControlDCSC =
  openfmb.circuitsegmentservicemodule.CircuitSegmentControlDCSCKt.Dsl._create(openfmb.circuitsegmentservicemodule.CircuitSegmentControlDCSC.newBuilder()).apply { block() }._build()
/**
 * ```
 * OpenFMB specialization for circuit segment service control, DCSC (Distributed Coordination
 * Service Control), following 61850 naming convention.
 * ```
 *
 * Protobuf type `circuitsegmentservicemodule.CircuitSegmentControlDCSC`
 */
public object CircuitSegmentControlDCSCKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: openfmb.circuitsegmentservicemodule.CircuitSegmentControlDCSC.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: openfmb.circuitsegmentservicemodule.CircuitSegmentControlDCSC.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): openfmb.circuitsegmentservicemodule.CircuitSegmentControlDCSC = _builder.build()

    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.LogicalNodeForControl logicalNodeForControl = 1 [(.uml.option_parent_message) = true];`
     */
    public var logicalNodeForControl: openfmb.commonmodule.LogicalNodeForControl
      @kotlin.jvm.JvmName("getLogicalNodeForControl")
        get() = _builder.logicalNodeForControl
      @kotlin.jvm.JvmName("setLogicalNodeForControl")
        set(value) {
        _builder.logicalNodeForControl = value
      }
    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.LogicalNodeForControl logicalNodeForControl = 1 [(.uml.option_parent_message) = true];`
     */
    public fun clearLogicalNodeForControl() {
      _builder.clearLogicalNodeForControl()
    }
    /**
     * ```
     * UML inherited base object
     * ```
     *
     * `.commonmodule.LogicalNodeForControl logicalNodeForControl = 1 [(.uml.option_parent_message) = true];`
     * @return Whether the logicalNodeForControl field is set.
     */
    public fun hasLogicalNodeForControl(): kotlin.Boolean {
      return _builder.hasLogicalNodeForControl()
    }

    public val CircuitSegmentControlDCSCKt.Dsl.logicalNodeForControlOrNull: openfmb.commonmodule.LogicalNodeForControl?
      get() = _builder.logicalNodeForControlOrNull

    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.circuitsegmentservicemodule.ENG_CircuitSegmentServiceModeKind CircuitSegmentServiceMode = 2;`
     */
    public var circuitSegmentServiceMode: openfmb.circuitsegmentservicemodule.ENG_CircuitSegmentServiceModeKind
      @kotlin.jvm.JvmName("getCircuitSegmentServiceMode")
        get() = _builder.circuitSegmentServiceMode
      @kotlin.jvm.JvmName("setCircuitSegmentServiceMode")
        set(value) {
        _builder.circuitSegmentServiceMode = value
      }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.circuitsegmentservicemodule.ENG_CircuitSegmentServiceModeKind CircuitSegmentServiceMode = 2;`
     */
    public fun clearCircuitSegmentServiceMode() {
      _builder.clearCircuitSegmentServiceMode()
    }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.circuitsegmentservicemodule.ENG_CircuitSegmentServiceModeKind CircuitSegmentServiceMode = 2;`
     * @return Whether the circuitSegmentServiceMode field is set.
     */
    public fun hasCircuitSegmentServiceMode(): kotlin.Boolean {
      return _builder.hasCircuitSegmentServiceMode()
    }

    public val CircuitSegmentControlDCSCKt.Dsl.circuitSegmentServiceModeOrNull: openfmb.circuitsegmentservicemodule.ENG_CircuitSegmentServiceModeKind?
      get() = _builder.circuitSegmentServiceModeOrNull

    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.ControlDPC Island = 3;`
     */
    public var island: openfmb.commonmodule.ControlDPC
      @kotlin.jvm.JvmName("getIsland")
        get() = _builder.island
      @kotlin.jvm.JvmName("setIsland")
        set(value) {
        _builder.island = value
      }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.ControlDPC Island = 3;`
     */
    public fun clearIsland() {
      _builder.clearIsland()
    }
    /**
     * ```
     * MISSING DOCUMENTATION!!!
     * ```
     *
     * `.commonmodule.ControlDPC Island = 3;`
     * @return Whether the island field is set.
     */
    public fun hasIsland(): kotlin.Boolean {
      return _builder.hasIsland()
    }

    public val CircuitSegmentControlDCSCKt.Dsl.islandOrNull: openfmb.commonmodule.ControlDPC?
      get() = _builder.islandOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun openfmb.circuitsegmentservicemodule.CircuitSegmentControlDCSC.copy(block: `openfmb.circuitsegmentservicemodule`.CircuitSegmentControlDCSCKt.Dsl.() -> kotlin.Unit): openfmb.circuitsegmentservicemodule.CircuitSegmentControlDCSC =
  `openfmb.circuitsegmentservicemodule`.CircuitSegmentControlDCSCKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val openfmb.circuitsegmentservicemodule.CircuitSegmentControlDCSCOrBuilder.logicalNodeForControlOrNull: openfmb.commonmodule.LogicalNodeForControl?
  get() = if (hasLogicalNodeForControl()) getLogicalNodeForControl() else null

public val openfmb.circuitsegmentservicemodule.CircuitSegmentControlDCSCOrBuilder.circuitSegmentServiceModeOrNull: openfmb.circuitsegmentservicemodule.ENG_CircuitSegmentServiceModeKind?
  get() = if (hasCircuitSegmentServiceMode()) getCircuitSegmentServiceMode() else null

public val openfmb.circuitsegmentservicemodule.CircuitSegmentControlDCSCOrBuilder.islandOrNull: openfmb.commonmodule.ControlDPC?
  get() = if (hasIsland()) getIsland() else null

